### ISSUE TITLE
ly consumes a lot of CPU time

### ISSUE THREAD

**Issue by d5244af6a0** [fairyglade/ly#125]
Hello.
I am using ArchLinux on an armv7h processor. I recently updated the version of ly, and found that ly began to consume a lot of CPU time.
I used strace to connect to the process and this is what I see in the log (a lot of lines that repeat cyclically):

openat(AT_FDCWD, "/dev/console", O_RDONLY) = 7
ioctl(7, KDGKBLED, 0xbecfabcb)          = -1 ENOTTY (Inappropriate ioctl for device)
close(7)                                = 0
write(3, "\33[35;69H\33[35;69H", 16)    = 16
read(4, "", 4096)                       = 0
_newselect(6, [4 5], NULL, NULL, {tv_sec=0, tv_usec=5000}) = 0 (Timeout)
openat(AT_FDCWD, "/dev/console", O_RDONLY) = 7
ioctl(7, KDGKBLED, 0xbecfabcb)          = -1 ENOTTY (Inappropriate ioctl for device)
close(7)                                = 0
write(3, "\33[35;69H\33[35;69H", 16)    = 16
read(4, "", 4096)                       = 0
_newselect(6, [4 5], NULL, NULL, {tv_sec=0, tv_usec=5000}) = 0 (Timeout)

The version of the program, as the package manager shows it to me, is: v0.3.0.r3.g4c17b2f

Maybe there is an opportunity to understand what does not work as it should?

![ly](https://user-images.githubusercontent.com/29113859/65480278-5433d380-deaa-11e9-8901-8eac2a6719c7.png)

**Comment by cylgom** [comment]
This happens because I used sleep() to wait between frames, which is not very efficient under Linux. With signals coming from a system timer, the scheduler works a lot more like intended and the CPU usage drops. I will try to fix this at some point :)

**Comment by sighoya** [comment]
>The state of the locking keys seems to be unavailable on your system

That's not true, I have locking keys (caps lock, num lock and scroll lock) on my keyboard and yield still the same results as @d5244af6a0:

```c
write(3, "\33[35;69H\33[35;69H", 16)    = 16
read(4, "", 4096)                       = 0
select(6, [4 5], NULL, NULL, {tv_sec=0, tv_usec=5000}) = 0 (Timeout)
openat(AT_FDCWD, "/dev/console", O_RDONLY) = 7
ioctl(7, KDGKBLED, 0x7ffe89e7f69f)      = 0
close(7)                                = 0
write(3, "\33[35;69H\33[35;69H", 16)    = 16
read(4, "", 4096)                       = 0
select(6, [4 5], NULL, NULL, {tv_sec=0, tv_usec=5000}) = 0 (Timeout)
openat(AT_FDCWD, "/dev/console", O_RDONLY) = 7
ioctl(7, KDGKBLED, 0x7ffe89e7f69f)      = 0
close(7)                                = 0
write(3, "\33[35;69H\33[35;69H", 16)    = 16
read(4, "", 4096)                       = 0
select(6, [4 5], NULL, NULL, {tv_sec=0, tv_usec=5000}) = 0 (Timeout)
openat(AT_FDCWD, "/dev/console", O_RDONLY) = 7
ioctl(7, KDGKBLED, 0x7ffe89e7f69f)      = 0
close(7)                                = 0
```
What's the state on this, is there an option to deactivate polling for caps/num/scroll lock in the config.ini?

**Comment by weust1979** [comment]
I notice this issue on my FreeBSD 12.2 on a 5th gen Intel i3 NUC as well.
between 20 and 30% CPU utilization just sitting at the login not doing anything, no animations.

**Comment by apatrushev** [comment]
Same here:
* ubuntu 20.04
* laptop "msi prestige 15 a10sc"
* github master

**Comment by AnErrupTion** [comment]
Can anyone test this with the latest fix from master, especially with tb_poll_event?

**Comment by Barbaross93** [comment]
I running the latest HEAD as of today. I don't see excessive cpu usage without animations any more. As an aside, is it possible to change the rate of the animation?

**Comment by AnErrupTion** [comment]
> As an aside, is it possible to change the rate of the animation?
As of now I don't think so, but you can open an issue for that.
