### ISSUE TITLE
Background is white and can't be changed

### ISSUE THREAD

**Issue by maxigaz** [fairyglade/ly#146]
I've tried both ly 0.4.0 and the latest git version (installed from the AUR packages `ly` and `ly-git`, respectively) under Manjaro Linux + i3 and Sway. In both cases, the background is almost always white, although the line `bg=0` is commented out in `/etc/ly/config.ini` (which should default to black, I assume?). This makes the text somewhat hard to read.

I’ve tried uncommenting that line and I get the same results.

Also, I’ve found an example of setting the background and foreground in #80, but from my understanding, it is mentioned there that this option wouldn't work under tty. I don’t know if the situation has changed since then and if it has, what format/value is accepted in the current version.

**Comment by takagiy** [comment]
I hit the similar situation; In my case the bg and the fg were always black and white respectively and config did not seem to affect. I don't know what I'm missing, but I found a workaround finally.
I edited the `/lib/systemd/system/ly.service` appending a `ExecStartPre` line to modify tty's color pallet.

```
[Unit]
Description=TUI display manager
After=systemd-user-sessions.service plymouth-quit-wait.service
After=getty@tty2.service

[Service]
Type=idle
ExecStartPre=/usr/bin/printf '%%b' '\e]P0FFC5C4\e]P7FFFFFF\ec'
ExecStart=/usr/bin/ly
StandardInput=tty
TTYPath=/dev/tty2
TTYReset=yes
TTYVHangup=yes

[Install]
Alias=display-manager.service
```

The above example sets color0(bg) to `#FFC5C4` and color7(fg) to `#FFFFFF`.

**Comment by takagiy** [comment]
I found that `term_reset_cmd` in `/etc/ly/config.ini` also has to be modified to keep the colors after logging-in and while in second time login screen after logging-out again.

```
term_reset_cmd = /usr/bin/tput reset; /usr/bin/printf '%b' '\e]P7F1E9C7\e]P0090602\ec'
```

**Comment by hiukky** [comment]
@takagiy I tried the steps of your answer but I didn’t succeed here :/

**Comment by ArchKubi** [comment]
> I found that `term_reset_cmd` in `/etc/ly/config.ini` also has to be modified to keep the colors after logging-in and while in second time login screen after logging-out again.
> 
> ```
> term_reset_cmd = /usr/bin/tput reset; /usr/bin/printf '%b' '\e]P7F1E9C7\e]P0090602\ec'
> ```

P7F1E9C7 <----- is this color code?
