### ISSUE TITLE
add display-stopped-script

### ISSUE THREAD

**Issue by Doaxan** [fairyglade/ly#153]
Please add display-stopped-script for work with optimus-manager.
https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting

**Comment by yaourtiere** [comment]
It could be a great adding, not just for optimus-manager.
I mean anybody could want some script to launch after just after the Xsession closes. A proper implementation of that would be much benefit !

**Comment by AnErrupTion** [comment]
This issue is now tracked over at #499.
