### ISSUE TITLE
Buliding ly 0.5.0 fails on FreeBSD: fatal error: 'utmp.h' file not found

### ISSUE THREAD

**Issue by 0mp** [fairyglade/ly#184]
Hello,

I've tried to update the [FreeBSD port of ly](https://www.freshports.org/x11/ly/) recently.

I cannot build ly anymore of FreeBSD because there is no utmp.h on FreeBSD. FreeBSD switched to utmp**x** many years ago and remove utmp completely AFAIK.

Do you think it could be possible to switch to utmpx from utmp? At least Wikipedia claims that utmpx is actually somewhat standardized in contrast to utmp (https://en.wikipedia.org/wiki/Utmp#utmpx,_wtmpx_and_btmpx).

Cheers!

----

WIP patch for the port update: https://reviews.freebsd.org/D23897

**Comment by cylgom** [comment]
I will take a look after PR #183 is merged, thanks for reporting :)

**Comment by 0mp** [comment]
@cylgom Thanks!

**Comment by justfly1111** [comment]
i got it to compile earlier by changing a few lines in src/login.c i think it was and after a few edits here and there but the resulting package segfaulted i minely changed utmp to utmpx but it compiled with not too much effort if youd like i can try and find my work to compare and work on getting a working patch that doesnt segfault immeadately. after my segfault escapade for shits in giggles after reviewing it from /usr/local i did a pkg install ly and found it available precompiled and working with a couple lines appended to /etc/gettytab and quick edit in /etc/ttys and it  worked right out the box but im the type that prefers to compile all my own pkg disregard just realized this post is over a year old and with it available in pkg im quite sure the patch has already been submitted and commited

**Comment by AnErrupTion** [comment]
Fixed in https://github.com/fairyglade/ly/commit/2bc12549a18db544ac5515998c331b2e2be18742.
