### ISSUE TITLE
runit (and other inits) service for artix, void, gentoo

### ISSUE THREAD

**Issue by jackghg** [fairyglade/ly#190]
segfault at 0 in libc2-31.so after login (runit)

**Comment by ericonr** [comment]
I haven't attempted running this outside systemd-land yet. What system did you run it on?

**Comment by jackghg** [comment]
artix - runit - lxde. The segfault is simply a crash I think.
I have updates:
If i stop the service, login as root on tty1, run ly, at login it crash.
If i stop the service, login as the main user on tty1, run sudo ly, it works.

**Comment by jackghg** [comment]
Updated title (much better). 
Guys more and more people and distro lately are droping systemd. So would be great if you could make the service for the 2 or 3 of the most common inits. ...and test. I tryed ly on systemd and i really love it!

**Comment by jackghg** [comment]
It could be the same issue of the issues 138, 203. Could be related to elogind.

**Comment by jackghg** [comment]
I got ly to work on artix runit !!!

    deleted/uninstalled old ly files
    downloaded @cylgom and @drozdowsky ly
    copyed @cylgom /src/xsetup.sh , wsetup.sh to @drozdowsky ly (replacing @drozdowsky files (xsetup is almost empty))
    compiled / installed / enabled the service / rebooted

@drozdowsky fork doesnt crash, so with original setups it works !
Now considering that drozdowsky did small changes, the main ly could easly support our distros !

**Comment by GrbavaCigla** [comment]
Is there a fork for openrc? I am on gentoo. Couldn't make it run with inittab nor changing xdm config.

**Comment by jackghg** [comment]
> Is there a fork for openrc? I am on gentoo. Couldn't make it run with inittab nor changing xdm config.
Dont know. Try to write the service !

**Comment by GrbavaCigla** [comment]
Tried with one service I found in one of the overlays, didn't work

**Comment by jackghg** [comment]
if ly dont even start its a service problem.

**Comment by GrbavaCigla** [comment]
I am getting segfault both in agetty and openrc script

**Comment by pspiagicw** [comment]
I made a OpenRC Script . And it works in my case.

**Comment by pspiagicw** [comment]
I made a OpenRC script and it works in my case.

**Comment by pspiagicw** [comment]
It is here https://github.com/pspiagicw/ly

**Comment by GrbavaCigla** [comment]
Nice, will check it out!

**Comment by GrbavaCigla** [comment]
It works, but I have to switch to different tty every time and pam module doesn't work properly (doesnt create /run/user/1000 so I don't have sound because pulseaudio depends on it....)

**Comment by pspiagicw** [comment]
Sorry for not testing the sound.But anyway could you suggest some changes as it was created roughly looking at other rc-scripts.I have no info on writing a proper rc-init script.

**Comment by GrbavaCigla** [comment]
I think rc script isn't causing pulseaudio problem. I think PAM module doesn't work properly. I will have to debug it a little bit more. https://unix.stackexchange.com/questions/162900/what-is-this-folder-run-user-1000

I have no experience in writting rc init scripts, but I will try to find a way to start on tty1.

**Comment by AndreiSva** [comment]
> It works, but I have to switch to different tty every time and pam module doesn't work properly (doesnt create /run/user/1000 so I don't have sound because pulseaudio depends on it....)
@GrbavaCigla 

Any fix for this? Is it be possible to automatically switch the tty at boot using some script?

**Comment by GrbavaCigla** [comment]
TTY issue shouldn't be hard, but I don't know for `/run/user/1000` problem. I don't have much time, but I will try to fix it.

**Comment by GrbavaCigla** [comment]
Maybe elogind is the issue?

**Comment by negativeExponent** [comment]
Bumping this thread coz my issue seems related:

I am trying to run ly as the display manager for Obarun (s6/66). I have created the necessary service file, but it is unable to login. As soon as i entered username and passed, it loops back directly at the login screen with the "logged out" message.

Interestingly, i have used the ly from https://github.com/drozdowsky/ly-void and this worked fine.

**Comment by jackghg** [comment]
> apparently, the problem was that LANG is null, causing ly to fail in logging in. Im on Obarun (s6/66)

this would fix ly here ? make a pull request!

**Comment by qontinuum-dev** [comment]
Just pushed a ly package to Artix's Universe
For now it is just a package that removes the systemd service and that patches this lang thing
Still there is no service for now. The runit service I use (based on the one mentioned earlier) doesn't allow to change the LANG value for now, I guess I should execute env to do so but still there is no service provided because I don't think it is a good quality one.
Help is welcome but I will only support Artix implementations of the different services which will obviously need some tweaks to work on other ones.

**Comment by jackghg** [comment]
> 
> 
> Just pushed...
Thanks!

**Comment by GrbavaCigla** [comment]
@pspiagicw any news on this?

**Comment by Cavernosa** [comment]
@GrbavaCigla see #368

**Comment by jackghg** [comment]
also dinit !!!

**Comment by Cavernosa** [comment]
> also dinit !!!

If nobody is willing to actually do it, it will never get done ¯\_(ツ)_/¯

**Comment by AnErrupTion** [comment]
I believe all init systems mentioned in this issue are now supported by Ly, so I'm closing this issue.
