### ISSUE TITLE
elogind

### ISSUE THREAD

**Issue by ndowens** [fairyglade/ly#203]
Can you add support for elogind or something? Reason I ask is w/o using systemd, root is needed to even start ly. Or is there another solution to this that I am missing? Thanks

**Comment by raaron773** [comment]
I would really like elogind support as well. It doesn't work on Void linux for me.

**Comment by sofubi** [comment]
Also going to add that Void support would be great!

**Comment by jackghg** [comment]
I made the issue 190 "openrc, runit, s6 service for artix, void, gentoo", formely "segfault". 
Maybe the reason is not the init, but elogind. Maybe its the same issue. I use artix runit btw

**Comment by jackghg** [comment]
its strange anyway... elogind is a clone of logind... it should work...

**Comment by raaron773** [comment]
> its strange anyway... elogind is a clone of logind... ly should work...

Ly really needs a small update which fixes these issues.

**Comment by jackghg** [comment]
guys, have u tryed https://github.com/drozdowsky/ly-void ?

**Comment by raaron773** [comment]
> guys, have u tryed https://github.com/drozdowsky/ly-void ?

No D: Didn't even know it existed. Thank you! will give this a try right now!

**Comment by jackghg** [comment]
doesnt work here too (artix runit), but this time it doesnt seem to crash, i see no errors, look like it login , startx and quit...

**Comment by jackghg** [comment]
I got ly to work on artix runit !!!
- deleted/uninstalled old ly files
- downloaded @cylgom and @drozdowsky ly
- copyed @cylgom /src/xsetup.sh , wsetup.sh to @drozdowsky ly (replacing @drozdowsky files (xsetup is almost empty))
- compiled / installed / enabled the service / rebooted

@drozdowsky fork doesnt crash, so with original setups it works !
Now considering that drozdowsky did small changes, the main ly could easly support our distros !

**Comment by raaron773** [comment]
> I got ly to work on artix runit !!!
> -- (not sure if needed) installed xterm
> -- deleted/uninstalled old ly files
> -- downloaded @cylgom and @drozdowsky ly
> -- copyed @cylgom /src/xsetup.sh , wsetup.sh to @drozdowsky ly (replacing @drozdowsky files (xsetup is almost empty))
> -- compiled / installed / enabled the service / rebooted
> 
> @drozdowsky fork doesnt crash, so with original setups it works !
> Now considering that drozdowsky did small changes, the main ly could easly support our distros !
> (Or maybe he just forked an older version that doesnt crash)

Now this, this worked flawlessly. Thank you! appreciate it (:

**Comment by AnErrupTion** [comment]
This should already be fixed on master. Closing.
