### ISSUE TITLE
Feasibility as lockscreen.

### ISSUE THREAD

**Issue by pranjlp** [fairyglade/ly#204]
Could it be possible to use ly without logging out of the X session as a potential screen lock?

**Comment by Wrexes** [comment]
Just passing by to say I'd be interested too.

Currently I'm using i3-lock-fancy with a mini-script that picks a random [WhatTheCommit](whatthecommit.com) quote but I'd gladly change for Ly with Doomfire on.

**Comment by nullgemm** [comment]
As said in #291, I don't know if this is possible, and if it is it must be incredibly complex, closing for now :(
