### ISSUE TITLE
Black screen after logging in

### ISSUE THREAD

**Issue by ilchub** [fairyglade/ly#211]
Black screen with blinking underscope after logging in on Fedora 32(both proprietary and open-source NVidia driver)

**Comment by dhalucario** [comment]
I found the error and used `audit2allow` and `sepolicy` to generate a policy for ly to be useable with SELinux. Maybe we can add a step to the Makefile to generate and install the SELinux policies? Or go further and add a spec file so we can build rpms of ly on the Fedora Copr buildsystem.
[ly-selinux-policies.tar.gz.zip](https://github.com/nullgemm/ly/files/5922001/ly-selinux-policies.tar.gz.zip)

**Comment by dhalucario** [comment]
I found the error and used `audit2allow` and `sepolicy` to generate a policy for ly to be useable with SELinux. Maybe we can add a step to the Makefile to generate and install the SELinux policies? Or go further and add a spec file so we can build rpms of ly on the Fedora Copr buildsystem.

Here the policy I generated. You need to run the ly.sh as root to install it.
[ly.tar.gz](https://github.com/nullgemm/ly/files/5922013/ly.tar.gz)

**Comment by dhalucario** [comment]
Here is a first WIP for the spec file. We would need to add the `.te` file from above to the repo so I can actually write a make entry that compiles the module.

```
Name:       ly
Version:    0.5
Release:    2
Summary:    A TUI display manager
License:    WTFPL
BuildRequires: libxcb-devel
BuildRequires: pam-devel
Requires: libxcb
Requires: pam

%description
Ly is a lightweight TUI (ncurses-like) display manager for Linux and BSD.

%prep
rm -rf $RPM_BUILD_DIR/ly
rm -rf $RPM_BUILD_DIR/src
git clone https://github.com/nullgemm/ly.git src
cd $RPM_BUILD_DIR/src
make github

%build
cd src
make

%install
cd src
mkdir -p %{buildroot}/etc/
mkdir -p %{buildroot}/usr/bin/
mkdir -p %{buildroot}/usr/lib/systemd/system/
mkdir -p %{buildroot}/etc/pam.d/
DESTDIR="%{buildroot}" make install

%files
/usr/bin/ly
/usr/lib/systemd/system/ly.service
/etc/ly/lang/es.ini
/etc/ly/lang/pt.ini
/etc/ly/lang/ru.ini
/etc/ly/lang/en.ini
/etc/ly/lang/fr.ini
/etc/ly/lang/ro.ini
/etc/ly/xsetup.sh
/etc/ly/wsetup.sh
/etc/ly/config.ini
/etc/pam.d/ly

%changelog
```

**Comment by dhalucario** [comment]
I made a WIP Copr for ly
https://copr.fedorainfracloud.org/coprs/dhalucario/ly/

**Comment by dhalucario** [comment]
The WIP seems to work now properly.
You still need to enable the service and disable getty@tty2 by hand (and make sure that your systemd target is set to graphical `sudo systemctl set-default graphical.target`). Then it should work just fine.

**Comment by chaibronz** [comment]
> The WIP seems to work now properly.
> You still need to enable the service and disable getty@tty2 by hand (and make sure that your systemd target is set to graphical `sudo systemctl set-default graphical.target`). Then it should work just fine.

thanks for putting this together @dhalucario ! i was able to login with ly using your COPR build, however i had some other issues creep up: 1) being prompted for a password when starting firefox, 2) not being able to 'reboot' without sudo, and 3) not being able to launch dmenu on one of my wms. when I removed your build of ly everything went back to normal. is there anything in your ly policy, or any other packaged files, that would cause these changes? thanks

**Comment by dhalucario** [comment]
> > The WIP seems to work now properly.
> > You still need to enable the service and disable getty@tty2 by hand (and make sure that your systemd target is set to graphical `sudo systemctl set-default graphical.target`). Then it should work just fine.
> 
> thanks for putting this together @dhalucario ! i was able to login with ly using your COPR build, however i had some other issues creep up: 1) being prompted for a password when starting firefox, 2) not being able to 'reboot' without sudo, and 3) not being able to launch dmenu on one of my wms. when I removed your build of ly everything went back to normal. is there anything in your ly policy, or any other packaged files, that would cause these changes? thanks

I know that the display manager usually does a lot of initialization when it comes to permissions for specific tasks which I haven't completely figured out myself. I use awesome WM and I can use Firefox just fine. Maybe you could tell us more about your system so we can try to debug stuff.

1. How did you install Fedora? Did you use Fedora Workstation or Fedora Everything?
2. Also which desktop environment are you using?

I remember some DE's wanting the password for Firefox because its trying to access the keychain.

**Comment by dhalucario** [comment]
#310 I created a pull request for the files. It would be cool if we could add this to the repo.

**Comment by dhalucario** [comment]
@nullgemm

**Comment by nullgemm** [comment]
This is awesome  @dhalucario, let's discuss it on the PR thread: #310

**Comment by KouranliKe** [comment]
I tried using the copr repo in Fedora 36 (KDE) and it didn't even want to download the package. Also, the selinux permission script provided above returns an error message (I am not in my computer rn but when I get home I'll qoute it). How can I give Ly a selinux permission manually? I am dying to use it as my display manager over sddm.

**Comment by AnErrupTion** [comment]
This issue is now tracked on #494.
