### ISSUE TITLE
Whish autologin feature

### ISSUE THREAD

**Issue by Vincenzo-Petrolo** [fairyglade/ly#212]
Hi there, is it possible to add the autolgin feature? Possibily by adding entries in the config file.
I cloned your project and tried to modify it by myself, but it lacks of comment and it is a bit difficult, but not impossible, to get what i was looking for.

Have a nice day :)

**Comment by jackghg** [comment]
what ? there is no autologin ???

**Comment by schijtreiger** [comment]
Autologin sort of defeats the purpose of a login manager, no?

**Comment by smdotdev** [comment]
Would love to have that feature, as for encrypted systems, it's sometimes become very cumbersome to type two password for quick login....

**Comment by tekakutli** [comment]
> Autologin sort of defeats the purpose of a login manager, no?

when you are powering-on the pc, you likely are guarding it
thats why I like autologin, but only when powering-on
if the pc suspends do to inactivity I do hope for the login to be required

this is implemented in lightdm and gdm, I do hope for this feature

**Comment by nullgemm** [comment]
tracking this in #266, thanks for the suggestion :)

**Comment by jackghg** [comment]
@nullgemm  are you restarting the development of ly ?
