### ISSUE TITLE
Multis-screen compatibility ?

### ISSUE THREAD

**Issue by SirWrexes** [fairyglade/ly#213]
Hey !

I am having issues with multi-screen display and I'm wondering if maybe Ly is the issue.

I have done a minimalist GUI setup on Arch Linux (latest) with :
  - Ly as Display manager
  - Xorg as Display server
  - i3-wm as window-manager

My graphics card is an NVidia GTX-1060 and I chose proprietary drivers (nvidia & nvidia-prime + nvidia-utils & nvidia-settings).

I also installed xorg-randr, autorandr and even tried [believer](https://github.com/michcioperz/believer), but with no success.

Xorg and i3 are known to fully support multihead, so my question is the following :
Am I doing something terribly wrong or is it just Ly that doesn't fit my needs ?

**Comment by ExploHash** [comment]
What kind of issues are you experiencing? I also have this setup except instead of i3 i have awesome and it works perfecty fine.

**Comment by Wrexes** [comment]
Well the secondary screen just isn't detected.
It never shows up in autorandr's output or shows up as off/disconnected.
It's not in my NVidia settings either.
It acts as if nothing is plugged in.

**Comment by ExploHash** [comment]
Okay, that doesn't sound like it has something to do with ly. Have you tried starting it with [xinit](https://wiki.archlinux.org/index.php/Xinit)? That way you can make sure it isn't ly's fault (most likely isnt). I had many struggles with nvidia drivers in the past, and fucking around with the xorg server config fixed it.

**Comment by Wrexes** [comment]
Interesting. I'll try fiddling with them. If I find a solution I'll come back here. :)

**Comment by nullgemm** [comment]
Ly does not configure displays directly, this should be done in `.xprofile`
