### ISSUE TITLE
Include git submodule dependencies in release tarballs

### ISSUE THREAD

**Issue by cinerea0** [fairyglade/ly#226]
Building ly does not work well when downloading a release tarball because the tarball is not a git repository and the build dependencies are git submodules. It would be a great improvement if the release tarballs came with the git submodule dependencies pre-downloaded and in the correct position.

**Comment by nullgemm** [comment]
Ly's build system and release process are garbage, and I am very sorry you all have to endure this situation. I should definitely fix this someday, now I [know better](https://github.com/nullgemm/globox).
