### ISSUE TITLE
Moving .lyxauth to XDG_RUNTIME_DIR

### ISSUE THREAD

**Issue by Kljunas2** [fairyglade/ly#233]
Runtime directory might be more appropriate for xauthority file. Additionally, I think XDG_CONFIG_HOME might not be set yet, so it can litter the home directory.

**Comment by DusanLesan** [comment]
Anything but home would be better

**Comment by UtkarshVerma** [comment]
Yes, storing it in `XDG_RUNTIME_DIR` would be better. That's what Arch also suggests in the XDG Base Directory.

https://wiki.archlinux.org/title/XDG_Base_Directory

**Comment by qmild** [comment]
Has this been implemented yet?

If not, does anyone know a safe way to move .lyxauth out of the home directory??

**Comment by UtkarshVerma** [comment]
I have a fork which reads XDG_RUNTIME_DIR for storing the file.
https://github.com/UtkarshVerma/ly

**Comment by nullgemm** [comment]
Ly already stores its `.lyxauth` file in the `XDG_CONFIG_HOME` directory when available, but I guess `XDG_RUNTIME_DIR` would be better indeed

**Comment by Cavernosa** [comment]
Added in #330 and #419
