### ISSUE TITLE
Teamviewer support?

### ISSUE THREAD

**Issue by romariorobby** [fairyglade/ly#234]
its supposed to be worked on ly isn't? according to this [Aur pinned comment](https://aur.archlinux.org/packages/teamviewer/)

**Comment by danielfomin96** [comment]
For me Teamviewer does not work with ly

**Comment by danielfomin96** [comment]
For me it works with sddm.  So I compared the environment variables, but even after adding the missing variables to ly, it still does not work.

**Comment by juster-0** [comment]
[ly-reloaded](https://github.com/SartoxSoftware/ly-reloaded) works fine with teamviewer, so you can install the fork. And [AUR](https://aur.archlinux.org/packages/ly-reloaded-git) also available.

**Comment by romariorobby** [comment]
> [ly-reloaded](https://github.com/SartoxSoftware/ly-reloaded) works fine with teamviewer, so you can install the fork. And [AUR](https://aur.archlinux.org/packages/ly-reloaded-git) also available.

Cool. Thanks for letting me know. I appreciated. Gotta try later!
