### ISSUE TITLE
Circle / Bullet Character as Password Asterisk

### ISSUE THREAD

**Issue by ElectricPrism** [fairyglade/ly#237]
I am wondering if there's a list of characters that can be used. I tried circles and bullets from several characters from various char-sets. I was able to use the period symbol which looked okay but I am wondering if there's a "circle" other than the character o or O compatible.

**Comment by bandithijo** [comment]
@ElectricPrism 
There are variable `asterisk` on **config.ini**.
You can define your own char for mask the password.
```
# the char used to mask the password
#asterisk = *
#asterisk = o
```
https://github.com/nullgemm/ly/blob/77f6958241646e3f315f27bc38212c3c4e1e7a8d/res/config.ini#L8

**Comment by AnErrupTion** [comment]
This isn't strictly an Ly-related issue, so I'm closing it.
