### ISSUE TITLE
Enabling ly on S6/66 (Obarun)

### ISSUE THREAD

**Issue by anthony-beckett** [fairyglade/ly#242]
I've followed the [Obarun guide](https://wiki.obarun.org/doku.php?id=dbus_and_dm) for enabling DM's and I've tried building ly from source as well as installing it from the AUR, both result in the same answer. When arriving at the step to enable ly, this: 
```zsh 
$ sudo 66-enable dbus consolekit ly
```
I'm greeted with the following error: `66-enable: fatal: unable to resolve source path of: ly`
Despite being able to manually start ly, by simply typing `$ ly`

**Comment by AnErrupTion** [comment]
Since S6 support has been mainlined, I believe you can just enable it using the instructions in the README.
