### ISSUE TITLE
Ly ignores config.ini

### ISSUE THREAD

**Issue by big-caballito** [fairyglade/ly#243]
Manjaro ARMv8 on Raspberry Pi 4
compiled ly from source (via AUR package ly-git) and edited /etc/ly/config.ini so that
```
tty = 1
...
xsessions = /usr/share/xsessions
```
**But** when I reboot, ly is on tty2 and my WM (awesome -- it does have a `chmod +x`'d .desktop file in xsessions folder)  does not show up in the list.

**Comment by AnErrupTion** [comment]
Does the config file reset or not?

**Comment by Kritiqual** [comment]
I have read a thread about the DM is failed to do sowething  :| and fall back to tty2, but I forgot where it is, lol

**Comment by nullgemm** [comment]
The service file should be changed as well so systemd starts it on tty1. Can you do that and try again?
