### ISSUE TITLE
Fails to install on Alpine Linux edge

### ISSUE THREAD

**Issue by IAMSolaara** [fairyglade/ly#255]
I'm trying to install Ly with `sudo make install` but `install` complains about Z being an unrecognized option:
```
$ sudo make install
installing
install: unrecognized option: Z
BusyBox v1.32.0 () multi-call binary.

Usage: install [-cdDsp] [-o USER] [-g GRP] [-m MODE] [-t DIR] [SOURCE]... DEST

Copy files and set attributes

        -c      Just copy (default)
        -d      Create directories
        -D      Create leading target directories
        -s      Strip symbol table
        -p      Preserve date
        -o USER Set ownership
        -g GRP  Set group ownership
        -m MODE Set permissions
        -t DIR  Install to DIR
make: *** [makefile:74: install] Error 1
```

It otherwise compiled just fine...

**Comment by lorecast162** [comment]
These are the contents of my `/etc/os-release` btw if you need to know:
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.13.0_alpha20200917
PRETTY_NAME="Alpine Linux edge"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

**Comment by kdkasad** [comment]
Your `os-release` is not important here. The problem is that `install(1)` (provided by busybox) does not recognize the `-Z` flag. If you run `man 1 install`, you'll see that the `-Z` flag is used for SELinux policies. Since Alpine Linux does not use SELinux, you can remove the `-Z` flag and try installing again.

**Comment by lolazogarbazno** [comment]
> Your `os-release` is not important here. The problem is that `install(1)` (provided by busybox) does not recognize the `-Z` flag. If you run `man 1 install`, you'll see that the `-Z` flag is used for SELinux policies. Since Alpine Linux does not use SELinux, you can remove the `-Z` flag and try installing again.

hi, i'm having the same problem, where do i have to remove -z flag?

**Comment by phanirithvij** [comment]
@lorecast162 I've tried compiling with this (in my fork I just removed the Z's from the makefile)

```shell
apk add libxcb-dev linux-headers musl-dev gcc linux-pam-dev make git
git clone --recurse-submodules https://github.com/phanirithvij/ly
make
make install
make installopenrc
rc-update add ly default
```

But when I run the ly I get SIGSEGV.

**Comment by DriNeo** [comment]
The readme should be updated to warn about GNU Coreutils dependency !
