### ISSUE TITLE
ly Partially Breaks KDE Theming

### ISSUE THREAD

**Issue by proudmuslim-dev** [fairyglade/ly#256]
OS: Arch Linux
DE: KDE Plasma (latest)

I made the switch from sddm to ly just now, as I plan on trying out other window managers in the process. However, upon rebooting, my themes are semi broken.

As you can see in this image, using ly makes it completely ignore my application style. 

![image](https://user-images.githubusercontent.com/69869443/101526151-22891a00-3941-11eb-8a50-7fdf59ae2045.png)

My apologies as I cannot write a more detailed report of all the things that are broken due to it being finals week at my school.

**Comment by AnErrupTion** [comment]
Is there a way you could send the output of `printenv` on both SDDM and Ly?

**Comment by AnErrupTion** [comment]
This issue seems to be fixed with the Zig rewrite.
