### ISSUE TITLE
sudo make run fails

### ISSUE THREAD

**Issue by Skeird** [fairyglade/ly#258]
OS: Debian 10 Buster on VirtualBox 6.1.16
WM: i3

I fetched the github submodules and compiled but when I run `sudo make run` Ly does not run and I only get a default tty login.

**Comment by AnErrupTion** [comment]
You're not supposed to run Ly like this. Running it without `sudo` (like `make run` or now `zig build run`) is fine for poking around with the UI, but running it with root privileges is not supported and will cause issues.
