### ISSUE TITLE
ly launches inside terminal when running inxi -Fxa

### ISSUE THREAD

**Issue by ojsl1** [fairyglade/ly#264]
OS: Arch Linux
DE: Happens on both herbstluftwm and KDE

Killing the launched ly with ctrl+c starts inxi and prints the -Fxa information normally.

Pictured below all three flags running fine alone but not together, running the same flags `inxi -Fxa` on my separate manjaro KDE machine with the SDDM login manager works fine. I feel like this is a ly related issue, I'm not 100% sure.
![screenshot](https://user-images.githubusercontent.com/10965741/103513810-090dbc00-4e74-11eb-928d-6c36fd3fa9de.png)

**Comment by UltraBlackLinux** [comment]
Experiencing this as well. Please fix this :/

**Comment by AnErrupTion** [comment]
This issue seems to be fixed with the Zig rewrite.
