### ISSUE TITLE
Chrome doesn't start after logout and login using sway

### ISSUE THREAD

**Issue by zsolt-donca** [fairyglade/ly#274]
I am using sway as my Wayland compositor and window manager. If I am using `ly` to log in to sway, then logout, and log back in, Chrome no longer starts. There are no error messages logged if I start chrome from the terminal. 

There are no issues on the first time I log into sway. Also, if I am starting sway without a display manager (directly from TTY), then there are no issues after logging out and logging back in - this issue is specific to `ly`.

I am on Arch Linux, using the official package `ly 0.5.2-2`. I am using `google-chrome-dev` version `90.0.4400.8-1` from the AUR.

**Comment by Flashs** [comment]
I've ran into similar issues, running the same setup.

**Comment by AnErrupTion** [comment]
Is there a way you could provide more information about this? I guess there's some sort of debug/verbose mode in Chrome, try to find it (if there's none then I don't know for now, but this seems like an environment variable issue)
