### ISSUE TITLE
Need help setting up ly on Gentoo

### ISSUE THREAD

**Issue by AndreiSva** [fairyglade/ly#275]
I've been using Ly for a long time and I love it's simplicity and performance. Recently I've switched to Gentoo but I couldn't get Ly working.

**Comment by doonoo** [comment]
#190 this issue should probably have a solution

**Comment by misss13** [comment]
Same here my ly is working partly I managed to compile it and run it but authentication isn't working at all

**Comment by negativeExponent** [comment]
> Same here my ly is working partly I managed to compile it and run it but authentication isn't working at all

you can try this and see if it works on your end. the issue was that LANG was empty when ly gets called.
https://github.com/nullgemm/ly/issues/216#issuecomment-801525253
