### ISSUE TITLE
Can only login with sudo?

### ISSUE THREAD

**Issue by chaibronz** [fairyglade/ly#276]
Hello,

I'm trying to test ly out on my Fedora 33 install and when I login from the default screen, nothing happens. Ok, well I get a black screen with a flashing cursor on the top left side, but other than that, nothing happens. That said, if i go to a different tty and sudo killall ly, then sudo ly, I'm able to login from there. I'm wondering if ly needs to be started with sudo to work? and if so, how do i get that to work by default? 

EDIT: found a similar issue that identified this as an SELinux problem. Installed ly from the COPR dhalucario shared here (https://github.com/nullgemm/ly/issues/211#issuecomment-774833987)  and working as expected now.

**Comment by nullgemm** [comment]
#211 duplicate, but thanks for reporting :heart:
