### ISSUE TITLE
Error enabling ly.service

### ISSUE THREAD

**Issue by ctrl-alt-breathe** [fairyglade/ly#280]
I'm trying to install on my computer and when I run sudo systemctl enable ly.service, it says "failed to enable unit: File /etc/systemd/system/display-manager.service already exists and is a symlink to /lib/systemd/system/gdm3.service."

**Comment by An4cl3t0** [comment]
Be sure to remove GDM before, and after you can:
`sudo rm etc/systemd/system/display-manager.service`
