### ISSUE TITLE
Using ly as screen locker?

### ISSUE THREAD

**Issue by johnwuelk** [fairyglade/ly#291]
Thanks for this cool DM, it works well on my Debian i3 machine.
How can I use this as a screen lock though like f.i. i3lock?
If I run ly on the console it just outputs a preview but not the actual login screen.

**Comment by ThatOneCalculator** [comment]
I don't think you can, but xsimplelocker is pretty good.

**Comment by cizordj** [comment]
Well if you are on Debian then you can use i3lock-fancy as you screen locker.

**Comment by nullgemm** [comment]
I don't know if this is possible. If so, it's probably very complex to support: I don't think we will :(

**Comment by ThatOneCalculator** [comment]
> if you are on Debian

Why Debian? It's a program available on pretty much all distros

**Comment by cizordj** [comment]
@ThatOneCalculator cause I use Debian.
