### ISSUE TITLE
Auto login with ly 

### ISSUE THREAD

**Issue by ghost** [fairyglade/ly#292]
Hello . im just installed arch linux and installed your display manager and working great. Just one small thing, how can i make ly dm auto login into my account sir?

**Comment by nullgemm** [comment]
I don't plan to add auto-login support to Ly, there are simpler alternatives that allow you to do this already :)

**Comment by mfdorst** [comment]
Could you give an example of one of these alternatives?

**Comment by paperbenni** [comment]
I would also like an example. There might be alternatives, but absolutely none of them seem simple. Setting session and username in a config file and enabling the ly service seems a lot simpler, especially because it's for both Wayland and x11

**Comment by D3vil0p3r** [comment]
The autologin has been implemented or not? It is a must-have feature for a display manager

**Comment by drunkwolfs** [comment]
очень жаль!

**Comment by drunkwolfs** [comment]
> Я не планирую добавлять в Ly поддержку автовхода

Очень жаль!

**Comment by AnErrupTion** [comment]
@Shallrath This feature is now tracked at #552.
