### ISSUE TITLE
Bluetooth Breaks on Relog

### ISSUE THREAD

**Issue by ibrokemypie** [fairyglade/ly#293]
After logging in, connecting to a bluetooth device, logging out and then back in, the bluetooth device refuses to connect until the ly service is restarted. This does not occur with other display managers.

similar to #272

**Comment by AnErrupTion** [comment]
Hey @ibrokemypie, would you be able to try my ly fork to see if your problem is fixed? Since it is indeed similar to the issue you posted, and I already put a fix in the code (or I hope so, since I don't get the issue), I would like to know if you could try it.

https://github.com/SartoxOnlyGNU/ly-reloaded

**Comment by ibrokemypie** [comment]
I think that worked actually! I just created an up to date aur package for it here https://aur.archlinux.org/packages/ly-reloaded-git/

**Comment by AnErrupTion** [comment]
No problem, thanks for making it! I'm glad your problem got solved!

**Comment by markstos** [comment]
@AnErrupTion Is there a brief summary of what fixed the Bluetooth problem?

**Comment by markstos** [comment]
I'm guessing this was the fix. In #272 there's discussion of XDG_SESSION_ID not being set, and this patch make sure several related XDG variables are set: 

https://github.com/SartoxSoftware/ly-reloaded/commit/d3cc890534373f68a8f8fb62f72f15faa7ba8494

**Comment by nullgemm** [comment]
Can you confirm this is fixed now the first ly-reloaded patches were merged ?

**Comment by AnErrupTion** [comment]
This should be fixed in master already. Please open a new issue if the problem persists.
