### ISSUE TITLE
feature: add option for a command to run when ly starts

### ISSUE THREAD

**Issue by silentnoodlemaster** [fairyglade/ly#294]
equivalent to `greeter-setup-script` in lightdm

**Comment by AnErrupTion** [comment]
Basically auto-run?

**Comment by silentnoodlemaster** [comment]
yeah it would run just before or as the login dialog is drawn

**Comment by allmeta** [comment]
Maybe modify the PreExec in `/lib/systemd/system/ly.service`

**Comment by nullgemm** [comment]
I don't think we need a feature in Ly to achieve this
