### ISSUE TITLE
Usage with Nvidia prime manager?

### ISSUE THREAD

**Issue by IlmastroStefanuzzo** [fairyglade/ly#298]
Prime manager is an utility which allows to easily switch between integrated GPU and dedicated GPU.
[This](https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting#my-display-manager-is-not-sddm-lightdm-nor-sddm) is what their wiki says to do if the display manager one uses isn't ""supported""
> You must manually configure your display manager so that
> 1. It uses Xorg (no Wayland)
> 2. It runs the script /usr/bin/prime-offload just after starting its display server for the login screen
> 3. It runs the script /usr/bin/prime-switch as root after the current user has logged out.

Doing that with xorg-xinit looks like this:
```
/usr/bin/prime-offload
ssh-agent dwm  # Start window manager/desktop enviorment
sudo /usr/bin/prime-switch
```
How can I do the same thing with ly?

**Comment by ImALoooserOk** [comment]
you got a solution? I'm also having the same problem with running scripts with ly

**Comment by AnErrupTion** [comment]
@IlmastroStefanuzzo @ImALoooserOk Modify the file at ``/etc/ly/xsetup.sh`` (would be wsetup.sh for Wayland) and at the end, add your commands to launch PRIME manager.

**Comment by IlmastroStefanuzzo** [comment]
> @IlmastroStefanuzzo @ImALoooserOk Modify the file at `/etc/ly/xsetup.sh` (would be wsetup.sh for Wayland) and at the end, add your commands to launch PRIME manager.

Dude, I had lost hope in someone answering my question so I've been using LightDM for nearly a year. Thank you so much, I'll try that and share my result.

**Comment by IlmastroStefanuzzo** [comment]
Alright, I got optimus-manager (btw why did I call it "Nvidia prima manager" lol) to start by adding `/usr/bin/prime-offload` to the top of `/etc/ly/xsetup.sh`. So that's half of the job done, but I also need `sudo /usr/bin/prime-switch` to execute **after** the DE or WM session ends. What config file do I need to change?

**Comment by raihanadf** [comment]
bump, adding `/usr/bin/prime-offload` to the top of `xsetup.sh` sure does make the prime-offload to run. @IlmastroStefanuzzo do you have any updates on making `prime-switch` to work?

**Comment by IlmastroStefanuzzo** [comment]
@raihanadf I stoppped looking for how to do the `sudo /usr/bin/prime-switch` thing because, as long as you don't switch GPU mode, it isn't needed and I pretty much never switch from integrated GPU mode. Also, I've just built a PC with an AMD GPU.
But maybe I'll still do some research to get optimus-manager to work.

Fuck you, Nvidia.

**Comment by AnErrupTion** [comment]
> but I also need sudo /usr/bin/prime-switch to execute after the DE or WM session ends. What config file do I need to change?
Actually, there's no way to run a command when a session ends. Please open an issue for that if needed!
