### ISSUE TITLE
Error Text appears in password field.

### ISSUE THREAD

**Issue by KILLinefficiency** [fairyglade/ly#302]
Ly works perfect for me but, after some time, some random error / warning text appears in the password field. I can still type my password and log in, but the text just does not look good.

This is how it looks.

![ly_error](https://user-images.githubusercontent.com/43932047/129014786-6c6a093d-2766-49a1-a054-be14febf1fd8.jpeg)
[](url)

If any way of fixing this exists, please recommend.

**Comment by MaxGyver83** [comment]
Same here!

**Comment by nullgemm** [comment]
This is a known issue, everything that can be done to mitigate it has been done (#79, #305). Sadly we can't avoid it entirely.
