### ISSUE TITLE
Shell login as root

### ISSUE THREAD

**Issue by josephholten** [fairyglade/ly#308]
I have a fresh installation of arch in a VM for testing. I can login to a live tty as root and my user from the default linux login prompt, but I cannot login as root from ly. I get the error "pam transaction aborted". Loggin in as my user works just fine in ly.
In a different issue somebody commented on an unrelated problem that they too couldn't login as root into the shell from ly because of pam. It seemed they thought that was normal and not a error.
My question is, whether the problem lies with me, as this is simply a config issue on my side, whether this is a error, or whether it is impossible to log in to the shell as root from ly.

**Comment by josephholten** [comment]
I have a fresh installation of arch in a VM for testing. I can login to a live tty as root and my user from the default linux login prompt, but I cannot login as root from ly. I get the error "pam transaction aborted". Loggin in as my user works just fine in ly.
In a different issue somebody commented on an unrelated problem that they too couldn't login as root into the shell from ly because of pam. It seemed they thought that was normal and not a error. 
My **question** is, whether the problem lies with me, as this is simply a config issue on my side, whether this is a error, or whether it is impossible to log in to the shell as root from ly.

**Comment by NorthShad0w** [comment]
edit /etc/pam.d/login
remove or comment line include word "require"

**Comment by moodyhunter** [comment]
FYI @josephholten check out the file at `/etc/securetty`, this is the file regulating whether root can log in on a specific TTY or not, it's invoked by `auth       required     pam_securetty.so` in `/etc/pam.d/login`
