### ISSUE TITLE
password area corrupted by stdout / stderr

### ISSUE THREAD

**Issue by seonjunn** [fairyglade/ly#314]
Though I want my password area to only display asterisks with my keyboard input, other outputs are being printed into password area (ex. when I plug in usb device, `usbhid 3-2.4.1:1.2: can't add hid device blah blah..` is printed into password area). Sometimes those filthy texts are so long that it even goes beyond the login box. Can anyone help me fix this?

**Comment by MaxGyver83** [comment]
This seems to be the same issue as #302.
