### ISSUE TITLE
Scale is least-common-denominator on mutli-resolution displays

### ISSUE THREAD

**Issue by lorendias** [fairyglade/ly#316]
I have displays in different sizes at different resolutions. 1080p 1440p and 4k.
Ly is selecting the least-common-denominator size and the scale is wrong on the 1440p and 4k displays.

Would it be possible to have each display output at the correct resolution?

**Comment by nullgemm** [comment]
To be exact, Ly isn't selecting *anything*. For now, you must use your `.xinitrc` to configure your displays (On my laptop I call a script from my `.xinitrc` to detect which ports are being used and configure xrandr accordingly).

**Comment by ReazerDev** [comment]
Hi, could you provide an example, please?
I've got the same setup as @lorendias.

```
  1 #!/bin/sh
  2 
  3 if xrandr | grep " connected " | awk '{ print$1 }' | grep -q 'DP-2'; then
  4         xrandr --output DP-2 --mode 3480x2160
  5 fi
  6 
  7 if xrandr | grep " connected " | awk '{ print$1 }' | grep -q 'DP-3'; then
  8         xrandr --output DP-3 --mode 2560x1440
  9 fi
 10 
 11 if xrandr | grep " connected " | awk '{ print$1 }' | grep -q 'HDMI-0'; then
 12         xrandr --output HDMI-0 --mode 1920x1080
 13 fi
```

This is the script I've made to set up xrandr and I'm executing it inside `/etc/xprofile`/`~/.xprofile`.
But ly still doesn't use "fullscreen" on my 4K and 1440p monitors. It's only working on my 1080p one.

Animations don't work either, but I'm guessing that this is due ly not using the whole monitor?
