### ISSUE TITLE
Ly not displaying unicode characters

### ISSUE THREAD

**Issue by GregePorter** [fairyglade/ly#317]
LANG=en-US.UTF-8
so is LC_ALL

I've also tried updating the font-cache but that hasn't seemed to work.

For example, if I type, `printf "\u0009"`
a blank space appears instead of, I think, the copyright symbol.

Does anyone else have any suggestions?

**Comment by nullgemm** [comment]
> For example, if I type, `printf "\u0009"` a blank space appears instead of, I think, the copyright symbol.
This is not the copyright symbol, but a non-printing character, so it is normal your terminal doesn't show you anything :) Maybe some other software you use has broken unicode support and breaks the reference you are comparing your terminal against?
