### ISSUE TITLE
Position cursor in Login field by default if this is the first time you boot up

### ISSUE THREAD

**Issue by arcolinuxz** [fairyglade/ly#323]
ArcoLinux will embrace this new display manager into its ranks.
I noticed that when we do a clean install and the first time we boot up the cursor is in the field password.
I type my password and login.
I get rejected as my login name was never ever given.
Then I remember that the first time around I need to arrow up and type my login first.
Can you do something about the first time you ever login?
![ly](https://user-images.githubusercontent.com/36679406/145714440-89c453c4-b507-4e27-a746-c2cba7e3a1ec.jpg)

**Comment by AnErrupTion** [comment]
#352

**Comment by AnErrupTion** [comment]
#352 merged.
