### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by xAffan** [fairyglade/ly#324]
Please update the UI to include a profile picture displayed using a program named "catimg"

**Comment by Kritiqual** [comment]
Have you ever seen any TUI program has a picture, lol

**Comment by nullgemm** [comment]
I don't think it's worth adding so much new dependencies to Ly for this kind of cosmetic feature, although it would probably look very cool. Sorry :)

**Comment by xAffan** [comment]
It's just one dependency, that can be compiled using simple C. I hope you reconsider.
