### ISSUE TITLE
[Fixed]Infinite login loop

### ISSUE THREAD

**Issue by ThatOneDev-Code** [fairyglade/ly#326]
Think it has something to do with my xinitrc file but whenever i login, it throws me right back into the login screen. But when i run the startx cmd, dwm boots up just fine. Any help would be nice.
Thanks

**Comment by Dominilk** [comment]
Having the same problem

**Comment by AnErrupTion** [comment]
Closing this issue as solved since it was apparently fixed (but no solution was found).
