### ISSUE TITLE
Gnome Keyring isn't fully unlocked by ly

### ISSUE THREAD

**Issue by AgathaSorceress** [fairyglade/ly#331]
## Environment
ArchLinux `5.15.12-arch1-1`, ly `v0.5.3.r0.g4094d21` (AUR), bspwm `0.9.10` (community), gnome-keyring `40.0` (extra), minecraft-launcher `928-1` (AUR), element-desktop `1.9.8-1` (community)

---

I followed the [archwiki gnome keyring](https://wiki.archlinux.org/title/GNOME/Keyring#PAM_step) setup instructions and issue #228. 

Whenever I log in, the default keyring doesn't get unlocked.  
![image](https://user-images.githubusercontent.com/53269550/148412625-652ed22d-0449-48b4-9297-4821f1c9f28d.png)

Starting `element-desktop` *does* automatically unlock the keyring after this and it behaves as expected, however if I do the same with `minecraft-launcher`, the launcher unlocks the keyring and then gives me a `Something went wrong in the login process.` error and throws me back to the login screen.

*Update: `element-desktop` auto-unlocked the keyring only once, but now every time I reboot, it asks me for the keying password, which means that ly definitely didn't unlock the keyring*

Is there a way to make ly automatically unlock the default keyring?

My `/etc/pam.d/login`:
```ini
#%PAM-1.0

auth       required     pam_securetty.so
auth       requisite    pam_nologin.so
auth       include      system-local-login
auth	   optional     pam_gnome_keyring.so
account    include      system-local-login
session    include      system-local-login
password   include      system-local-login
session    optional     pam_gnome_keyring.so auto_start
```
My `/etc/pam.d/ly`:
```ini
#%PAM-1.0

auth       include      login
account    include      login
password   include      login
session    include      login
password   optional     pam_gnome_keyring.so
```

I have tried picking the `xinitrc` option when logging in with ly and using this `.xinitrc` file:
```bash
#!/bin/sh

eval $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

exec bspwm
```
I have also tried picking the `bspwm` option and adding this to the end of my `.config/bspwm/bspwmrc` file:
```bash
if [ -n "$DESKTOP_SESSION" ]; then
    eval $(gnome-keyring-daemon --start)
    export SSH_AUTH_SOCK
fi
```
My default keyring password matches the user password.
I also tried  deleting all files in `.local/share/keyrings/` and re-creating the keyring multiple times.

**Comment by Anatanokami** [comment]
I can relate to this issue. Having a slightly different setup (using Sway 1.6.1), I cannot seem to get gnome-keyring working when launching from LY.

Tried from `.config/sway/config` and `.zshenv` with the above mentioned way. My PAM config looks the same as well.

**Comment by markstos** [comment]
I'm the one who opened #228 and left the comment there about how I got it working: 

https://github.com/nullgemm/ly/issues/228#issuecomment-758748986

Some differences with what is posted above:

   - At the end of my `start-swith-with-gnome-keyring.sh` script, I call `/sbin/sway` directly, without using `exec`. The use of `exec` may be messing up the parent-child process relationship that' would otherwise be created. 
   - My `/etc/pam.d/ly` is currently as follows. There's no mention of gnome-keyring in there:

```
#%PAM-1.0

auth       include      login
account    include      login
password   include      login
session    include      login
```

**Comment by kunver400** [comment]
Can verify this on gnome, I have to unlock gnome-keyring manually, 
also keyboard shortcuts for launching apps (CTRL+ALT+T..etc) have a lot of delay if gnome-keyring is locked.

**Comment by kunver400** [comment]
Can verify this on gnome, I have to unlock gnome-keyring manually on xorg. 
On wayland no password prompt shows up and some apps don't start at all.

**Comment by abelayalew** [comment]
I just updated ly today and its working on arch gnome wayland!

**Comment by Sid127** [comment]
could this be related to DESKTOP_SESSION not being set by ly. I noticed it isn't being set as opposed to SDDM using i3-wm

**Comment by Sid127** [comment]
I did some investigation and learned that a few environment variables are missing, for some reason, as opposed to say SDDM. I also noticed that the session type is set to tty and not x11

[sddmenv.log](https://github.com/fairyglade/ly/files/10383366/sddmenv.log)
[lyenv.log](https://github.com/fairyglade/ly/files/10383368/lyenv.log)

**Comment by markstos** [comment]
My solution was ultimately to log into Sway directly from the console login, bypassing `ly` and any other display manager.

**Comment by Sid127** [comment]
Because I got the email for this and was brought back to the thread, I re-read [this](https://github.com/fairyglade/ly/issues/331#issuecomment-1025986161) post and out of curiosity, replaced ly's pam config with the one from sddm, and everything's working fine. Keyring is unlocked by default, all the env vars are set too.

For the session type being tty and not x11, I installed `ly-git` from the AUR instead of `ly`, and that worked perfectly as well!

For anyone else who needs this, here's the new pam config, in `/etc/pam.d/ly`
```
#%PAM-1.0

auth		include		system-login
-auth		optional	pam_gnome_keyring.so
-auth   optional  pam_kwallet5.so

account		include		system-login

password	include		system-login
-password	optional	pam_gnome_keyring.so use_authtok

session		optional	pam_keyinit.so force revoke
session		include		system-login
-session		optional	pam_gnome_keyring.so auto_start
-session  optional  pam_kwallet5.so auto_start
```

**Comment by ilikenwf** [comment]
> Because I got the email for this and was brought back to the thread, I re-read [this](https://github.com/fairyglade/ly/issues/331#issuecomment-1025986161) post and out of curiosity, replaced ly's pam config with the one from sddm, and everything's working fine. Keyring is unlocked by default, all the env vars are set too.
> 
> For the session type being tty and not x11, I installed `ly-git` from the AUR instead of `ly`, and that worked perfectly as well!
> 
> For anyone else who needs this, here's the new pam config, in `/etc/pam.d/ly`
> 
> ```
> #%PAM-1.0
> 
> auth		include		system-login
> -auth		optional	pam_gnome_keyring.so
> -auth   optional  pam_kwallet5.so
> 
> account		include		system-login
> 
> password	include		system-login
> -password	optional	pam_gnome_keyring.so use_authtok
> 
> session		optional	pam_keyinit.so force revoke
> session		include		system-login
> -session		optional	pam_gnome_keyring.so auto_start
> -session  optional  pam_kwallet5.so auto_start
> ```

I'm not sure having "-" prior to any line in that file is valid syntax?

**Comment by AnErrupTion** [comment]
@sylv-io I've just closed all issues as not planned (I was a bit lazy to create an Action that added a message, and GitHub offered a convenient way to bulk close all issues at once :D).
