### ISSUE TITLE
make ly play some SID chip music or midi

### ISSUE THREAD

**Issue by plasmoduck** [fairyglade/ly#332]
How can I make ly play some SID chip music or midi on the login page? I thought it would fit well with the doom fire animation to have it play the doom theme or something.

I figured we could have another function similar to F1 Shutdown. Something like F2 Music, then set it in the config.ini # command executed when pressing F2 'music_cmd = sidplay /path/to/music.sid'.

**Comment by nullgemm** [comment]
Being a tracked music lover myself I agree this would be very cool, but it's sadly waaaaaay out of scope. Even if it weren't, it would generate an insane amount of new issues, which really isn't what we need right now. Sadly, the desktop audio thing is also extremely radioactive under Linux, and there's a high chance we would break some people's audio setup.

This should rather be handled outside of Ly, and synchronized with the booting and login process with existing software.
If you dare so.
