### ISSUE TITLE
Feature: Add option to turn on numlock at startup.

### ISSUE THREAD

**Issue by smhd001** [fairyglade/ly#334]
equivalent to `Numlock=on` in sddm

**Comment by nullgemm** [comment]
I am not sure how this can be done, but if it's possible why not.

**Comment by NikitaBeloglazov** [comment]
_bump_

we need it! :)

**Comment by NikitaBeloglazov** [comment]
Seriously? No movement April 2022? Are you kidding me?

**Comment by AnErrupTion** [comment]
@NikitaBeloglazov Hello! Sorry there's not been much progress on this, but we're prioritizing bug fixes over features. I may try to get this feature done by v1.1.0, though.

**Comment by NikitaBeloglazov** [comment]
Thank you!! ❤️
