### ISSUE TITLE
[OpenRC] Can't shutdown or reboot after login

### ISSUE THREAD

**Issue by Cavernosa** [fairyglade/ly#343]
I'm using the OpenRC script from the [ly-gentoo fork](https://github.com/pspiagicw/ly-gentoo) with LANG patch from [here](https://gist.github.com/negativeExponent/a7c3181a2c736fecf76410989f412adc).

After login it's impossible to shutdown or reboot with `loginctl poweroff` command or any other poweroff command. The only way is pushing the power button, or logging out and pressing F1 or F2.

**Comment by nullgemm** [comment]
I can't investigate this easily and OpenRC isn't supported officially, but this issues seems to indicate something is wrong in Ly, so we should definitely investigate this. Any PRs adding OpenRC support is of course very welcome.

**Comment by terrencetec** [comment]
Hi, I am seeing a possibly same problem wtih Qtile.
I am on Arch Linux, 5.17.5-arch1-1.
After logging out and logging in, I can't use the ``reboot`` and ``shutdown`` commands without root privileges.

**Comment by Cavernosa** [comment]
I think i've found the issue. ly is clogging up openrc-run, because if i kill the ly process it unclogs and everything starts working as usual
This is what htop shows:
```
openrc default
    openrc-run /etc/init.d/ly --lockfd 15 start
        ly
            ly
                Xorg :0 vt1
                    Xorg :0 vt1
                i3
```
Which i'm pretty sure should have something like supervise-daemon or just ly instead of openrc-run
No idea how to fix it though

**Comment by barunslick** [comment]
I having the same issue on Arch + bspwm. Can't seem to use the command `shutdown`.

**Comment by pc00per** [comment]
This is because X is not running on the same tty that the login occurs. ly logins user into separate tty, which messes up loginctl logind session, which inturn breaks polkit actions.
