### ISSUE TITLE
settings problem

### ISSUE THREAD

**Issue by ArchKubi** [fairyglade/ly#346]
there is no document and wiki
ı search change color but here is no beginner solution
and more important there is no man page ???? why
![2022-04-27-211225_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/165592162-03cd9ab6-3b48-4c64-b166-943997d822a0.png)
thanks for this project but we need document for beginner user

**Comment by AnErrupTion** [comment]
I think what we need to do is in the help command of Ly, instead of telling the user to RTFM (which doesn't exist), we should tell something like "Please modify config values at /etc/ly/config.ini".
