### ISSUE TITLE
``variety`` doesn't work with ly

### ISSUE THREAD

**Issue by terrencetec** [fairyglade/ly#350]
Hi, I have recently switched from LightDM to ly.
However, I noticed I cannot use ``variety`` to set wallpapers anymore.
The background remains plain grey.
I can use ``feh --bg-scale ...`` to set wallpaper but I want to use ``variety`` to cycle through my wallpapers.
If I switch to back LightDM, ``variety`` works fine.

I am using Arch 5.17.5-arch1-1 kernel and Qtile.
Your help is very much appreciated.
Thanks.

**Comment by AnErrupTion** [comment]
This might be due to an unset environment variable. Will try to reproduce soon.

**Comment by sudokit** [comment]
Any fixes yet?
