### ISSUE TITLE
background image

### ISSUE THREAD

**Issue by evanescente-ondine** [fairyglade/ly#351]
Hi,
How would you go about showing a background picture instead of an animation ?
I wish to gaze at my wifu's perfect 2D beauty.
Can it be done now or should it be added to ly ?
Usually I have autologin, but ly is so neat, I look like a poweruser now, I keep it ;-)

**Comment by nullgemm** [comment]
As discussed in https://github.com/fairyglade/ly/issues/324, ASCII art background images and profile pictures won't make it into Ly, sorry :(
