### ISSUE TITLE
Ly breaking python installation.

### ISSUE THREAD

**Issue by sudokit** [fairyglade/ly#357]
Im not really sure how and why but for some reason switching to Ly as the display manager (login manager idk) breaks python installation. From what iv experienced its probably messing with PYTHONHOME env variable or another one i cant remember. Also its probably the cause for variety not working ( issue #350 ) since its a python application. Personally iv experienced it breaking blender too. 
You can try reproducing the error by setting Ly as display manager and trying to run some python file. It will say something like "ImportError: no module 'encodings' found". And ontop of the error you can see some env variables (probably) that arent set.

**Comment by sudokit** [comment]
Sorry forgot to add the bug label but can't add it anymore. Tried to but it just removes it

**Comment by JPenuchot** [comment]
I've had a similar issue where CMake couldn't find `LLVM_INSTALL_DIR` when using Ly. I don't know if Ly is missing a step or messing with one when setting the environment, but there's definitely something wrong.
