### ISSUE TITLE
Spacing for the colons

### ISSUE THREAD

**Issue by nightmare-tech** [fairyglade/ly#358]
Please make the colons of the "login" and "password" aligned. Example:
```
login    : username
password : ***********
```
OR 
```
   login :
password :
```
I personally think that the first one looks good...
PS: I love how easy it is to recommend design changes just with text :-)

**Comment by AnErrupTion** [comment]
The problem is that this would require modifying the language files, and thus would create an inconsistency, where a string has some extra spacing while the others don't. I don't think it would be elegant for what it would do.

**Comment by nightmare-tech** [comment]
Oh.. I didn't know that. Closing the issue.
