### ISSUE TITLE
Package names of dependencies for Fedora

### ISSUE THREAD

**Issue by nightmare-tech** [fairyglade/ly#360]
I was trying to install `ly` on Fedora vm and when I run make it shows errors:
- pam.h missing -- figured how to install thanks to  #348 
- Now the xcb.h is missing and I can't figure out the package name. 

Please provide the package names of the dependencies for Fedora too.

**Comment by Bango88** [comment]
Try to install this package https://pkgs.org/download/libXtst-devel ? I'm on arch so I cannot check, but with a quick google search I found this issue: https://github.com/go-vgo/robotgo/issues/19 which suggests installing this package: libxtst-dev, and the rpm equivalent is libXst-devel.

**Comment by nightmare-tech** [comment]
Yes, that did the trick.. 
For Fedora dependencies:
```
dnf install pam-devel libXtst-devel
```
Thanks closing this issue...
