### ISSUE TITLE
Authentication Error [Fedora 36]

### ISSUE THREAD

**Issue by nightmare-tech** [fairyglade/ly#363]
I installed `ly` on a fedora 36 VM and it is giving `authentication error`. But I can login with the same credentials any other tty. I will attach screenshots of the same.
My guess will be the white space between the colon and the actual space where you can write is messing with the username.
![Screenshot from 2022-05-15 16-02-14](https://user-images.githubusercontent.com/73050725/168468549-673f7f68-3b76-429f-ad3a-f83f7bb3d1a0.png)
![Screenshot from 2022-05-15 16-03-04](https://user-images.githubusercontent.com/73050725/168468551-a2d244f4-a345-43b4-b48a-57d421aad984.png)

**Comment by AnErrupTion** [comment]
So, you can't login to GNOME but you can login to a TTY via Ly, correct?

**Comment by nightmare-tech** [comment]
No, I cannot login to anything via Ly. But I can login via another TTY so that means I am putting in the right credentials.

**Comment by AnErrupTion** [comment]
Can you login as root?

**Comment by nightmare-tech** [comment]
So, I don't know why my root password was not the same for sudo, but I reset the root password with `sudo -i passwd`. And now the Ly login screen shows `logged out` for both `root` and my user `noname`. Same problem as #356 and blinking cursor for xorg.
![image](https://user-images.githubusercontent.com/73050725/168734614-e15e0cab-c7f7-4d99-9c89-fcaf8969e32b.png)

**Comment by nightmare-tech** [comment]
Its the same issue as #356 
So closing the issue. Thanks
