### ISSUE TITLE
Feature Request: Command backspace erases entire password

### ISSUE THREAD

**Issue by jsilve24** [fairyglade/ly#372]
Command backspace "C-<backspace>" is a pretty standard binding for delete back to whitespace or delete back word. When I enter my password wrong I am currently forced to delete every character. Would it be possible to add this binding (when cursor is at the end of the password field) to delete the entire entered password?

Seems like this would be a nice enhancement. 

Anyways thanks so much for putthing this package together. I love it. 

Best, 
Justin

**Comment by kefoster951** [comment]
@jsilve24 There is a config for clearing the password field on failed logins, if the config option "blank_password" is true the field is cleared automatically on Failure. 

There is also a keybinding already for clearing a field, it's ctrl^U. I hope these options are what you were looking for.

**Comment by jsilve24** [comment]
That is what I am looking for. Thank you. 

Justin
