### ISSUE TITLE
Feature: screen locker

### ISSUE THREAD

**Issue by isXander** [fairyglade/ly#375]
I have configured Ly on my system, but it looks very inconsistent when I lock my user session. KDE Plasma provides a SDDM-like locker. It would be great if ly brought support to be a locker also.

**Comment by Javi3y** [comment]
There is a project called lightdm-locker
I really want this in ly and it's the only reason why I'm not switching

**Comment by cloudybyte** [comment]
as already said in #204 this is probably not gonna happen anytime soon
