### ISSUE TITLE
not running autostart.sh script in dwm

### ISSUE THREAD

**Issue by MisustinIvan** [fairyglade/ly#376]
I have [this](https://dwm.suckless.org/patches/autostart/) patch installed in dwm, and it doesnt run the autostart.sh file on login.

the file is as following:

#! /bin/bash
lxsession &
picom &
dwmblocks &
/usr/bin/emacs --daemon &
xrandr --output HDMI1 --mode 1920x1200 --primary --left-of eDP1
nitrogen --restore
setxkbmap -layout us, cz -option 'grp:alt_shift_toggle'

it shows some errors after login, but doesnt show them long enough

**Comment by dement6d** [comment]
is the file named autostart.sh and in the ~/.dwm/ directory? i have the [dwm-autostart-20210120-cb3f58a.diff](https://dwm.suckless.org/patches/autostart/dwm-autostart-20210120-cb3f58a.diff) patch installed and working with ly
