### ISSUE TITLE
.xinitrc does not execute on login

### ISSUE THREAD

**Issue by surrealcereal** [fairyglade/ly#378]
OS: Arch Linux
Version: 0.5.3-0 (latest one on AUR)
wm: Awesome

Even though my .xinitrc is marked executable as seen below and contains a shebang, ly does not execute it on launch, which is apparent through the alacritty window not popping up as specified. When .xinitrc is executed through the command line with `./.xinitrc`, everything works fine.

`ls -la` for my .xinitrc:
.rwxr-xr-x  793 tuna 22 May 16:23  .xinitrc

Contents of my .xinitrc:
```
#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

picom &
xrandr --output "DP-4" --mode 1920x1080 --rate 144.00 --right-of "HDMI-0" --primary &
xrandr --output "HDMI-0" --mode 1920x1080 --rate 74.97 --left-of "DP-4" &
alacritty &
exec awesome
```

**Comment by Osrepnay** [comment]
I don't think display managers are usually supposed to use .xinitrc, instead whatever's in https://wiki.archlinux.org/title/Display_manager#Session_configuration

**Comment by surrealcereal** [comment]
> I don't think display managers are usually supposed to use .xinitrc, instead whatever's in https://wiki.archlinux.org/title/Display_manager#Session_configuration

Thanks, that solved it, specifically installing the xinit-xsession package. Talking about the .xinitrc in the README though is a bit misleading if that's the case
