### ISSUE TITLE
ly doesn't set DBUS_SESSION_BUS_ADDRESS for sessions

### ISSUE THREAD

**Issue by UtkarshVerma** [fairyglade/ly#380]
I use Arch Linux which has a systemd service for starting up dbus. If I log into a shell(without ly), I can access the session env var set by the service:

```
$ echo $DBUS_SESSION_BUS_ADDRESS
unix:path=/run/user/1000/bus
```

However, if I log into a session using ly, the variable is not accessible, because of which applications dependent on dbus fails (playerctl etc).

**Comment by quasigod-io** [comment]
This is causing issues for me too. I need to add dbus-launch to i3.desktop for flatpaks to work. This is reset when i3 updates.

**Comment by sagarreddypatil** [comment]
#384 related

**Comment by TheRealMothebad** [comment]
I'm having this issue on Arch as well. Switching to LightDM fixed it, but I would like to use ly when it is fixed.

**Comment by shvedes** [comment]
> I'm having this issue on Arch as well. Switching to LightDM fixed it, but I would like to use ly when it is fixed.

[here is the solution](https://github.com/fairyglade/ly/issues/384#issuecomment-1213103624)

**Comment by AnErrupTion** [comment]
@UtkarshVerma @michaelBelsanti @xi-pinmping @TheRealMothebad Can you guys check if this issue is fixed with the latest code on master? For me `DBUS_SESSION_BUS_ADDRESS` is set after logging in now.

**Comment by UtkarshVerma** [comment]
I stopped using `ly`, hence, I won't be able to test it.

**Comment by TheRealMothebad** [comment]
@AnErrupTion 
> @TheRealMothebad Can you guys check if this issue is fixed with the latest code on master? For me `DBUS_SESSION_BUS_ADDRESS` is set after logging in now.

I'm not smart enough to build from source (I know, I'm a bad linux user), but after running 1.0.2-1 from the AUR (which seems like it should have the change based on the build date?) the problem does not seem to be fixed. Here is what pipewire has to say about it when using ly (it runs no problem under lightdm):
`[E][00381.493243] mod.rt       | [     module-rt.c:  281 pw_rtkit_bus_get()] Failed to connect to session bus: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
[E][00381.495652] mod.protocol-native | [module-protocol-:  740 init_socket_name()] server 0x5947ad44a070: name pipewire-0 is not an absolute path and no runtime dir found. Set one of PIPEWIRE_RUNTIME_DIR, XDG_RUNTIME_DIR or USERPROFILE in the environment`

**Comment by shvedes** [comment]
Mind to close the issue?
