### ISSUE TITLE
No worky with Hyprland

### ISSUE THREAD

**Issue by Vagahbond** [fairyglade/ly#389]
When using with hyprland and waybar, the workspaces do not work whereas they work when launching the compositor from TTY.
See [this issue](https://github.com/vaxerski/Hyprland/issues/131).

Minor issue but I wanted to let you know.

**Comment by EPNero** [comment]
can confirm this is in fact an issue with `hyprland`, `hyprland-git` and `hyprland-bin` packages (from AUR.)

**Comment by bcorneglio** [comment]
I had it working with the aur package ly until today, I changed to the ly-git package and now it also doesn't work.
Changing back is not possible at the moment says another issue post.

But it does work with the package ly-reloaded-git.

**Comment by exkc** [comment]
it work

**Comment by Vagahbond** [comment]
If several of you can confirm it works, I guess you can close issue. 
I switched to Nix and SDDM is better integrated in it, so I cannot test anymore.
