### ISSUE TITLE
How to change the default paths in ly?

### ISSUE THREAD

**Issue by codehia** [fairyglade/ly#405]
I have been running into the issue of $PATH not found because of default PATH in ly config. I tried to add path into the config but since my path is 
```
 $HOME/.local/bin
 ````
The path list doesn't read the path properly and breaks at the `.`.

**Comment by AnErrupTion** [comment]
@codehia This is most likely related to https://github.com/nullgemm/configator/issues/2. Unfortunately, I can't merge PRs there, so I can't do anything (for now at least).
