### ISSUE TITLE
Not setting ZSH environment correctly

### ISSUE THREAD

**Issue by Shiny380** [fairyglade/ly#407]
I'm using Ubuntu 21.10 (Note with Regolith mashed on top of GNOME). Was using default gdm3.

When logged in via gdm3 my PATH is set as
```
/home/shiny/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/go/bin:/home/shiny/.poetry/bin
```

When logged in through Ly:
```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

This is missing the 2 `/home/shiny/` dirs (first and last) as well as `/usr/local/go/bin`

Possibly related issues: #357, #405

**Comment by Shiny380** [comment]
Made some progress
I'm using ZSH as my shell so in `/etc/ly/xsetup.sh` I added under the `*/zsh` case:
```
    [ -f $HOME/.profile ] && . $HOME/.profile
```
(seems this should be there anyway since it's a Bourne compatible shell)

Now my shell has the correct PATH however my application launcher (rofi) is still wrong.
When I run `rofi -run-command "echo $PATH" -show drun` it prints the correct path so not sure why it's still missing applications.

Seems possible that Ly is still not setting the PATH properly. also tried sourcing `/etc/environment` but made no difference.
**NOTE:** The missing applications from rofi are in `/snap/bin` which was present in PATH before I sourced `$HOME/.profile` (see original description)

**Comment by Shiny380** [comment]
Solved: realised `xsetup.sh` wasn't sourcing `/etc/profile` either for ZSH. whoops.
Will fork and do a PR

**Comment by sophronesis** [comment]
Same problem here, ly corrupts shell prompt

**Comment by LordSquigles** [comment]
I'm not sure why ly does it differently than other display managers, but I just commented everything in /etc/ly/xsetup.sh after the switch-case and sourced the global X session script and it solved all my problems. After commenting, this was the line I added:

. /etc/X11/Xsession

**Comment by Staninna** [comment]
@Shiny380 Idk if this is still relevant but the zsh shell doesn't source the `~/.profile` file instead it sources its own file `~/.zprofile`

**Comment by AnErrupTion** [comment]
This seems like a shell-specific matter, closing.

**Comment by frankier** [comment]
Why was this closed? The branch for every other shell, including the default sources `/etc/profile`.
