### ISSUE TITLE
/usr/bin/X vs /usr/bin/startx

### ISSUE THREAD

**Issue by LiveEmily** [fairyglade/ly#408]
So I recently got to know of Ly and wanted to start using it, everything worked fine up until Ly tried to start my graphical environment (DWM with Xorg using Intel-i965). I didn't see any errors or warnings on either Ly or Xorg side, which was odd.

The fix for me was to change ``/usr/bin/X`` for ``/usr/bin/startx`` within ``/etc/ly/config.ini``, I personally always used startx from the TTY and this resolved every issue I had. What exactly is the difference between calling X directly and using xinit (startx)? And how could I remedy my .xinitrc to work with the X binary instead.

```ini
#/etc/ly/config.ini
animate = false
asterisk = *
blank_password = true
console_dev = /dev/console
default_input = 1
hide_borders =  false
input_len = 34
lang = en
load = true
max_desktop_len = 100
max_login_len = 255
max_password_len = 255
mcookie_cmd = /usr/bin/mcookie
min_refresh_delta = 5
path = /sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin
restart_cmd = /sbin/shutdown -r now
save = true
save_file = /etc/ly/save
service_name = ly
shutdown_cmd = /sbin/shutdown -a now
term_reset_cmd = /usr/bin/tput reset
tty = 2
x_cmd = /usr/bin/startx
x_cmd_setup = /etc/ly/xsetup.sh
xauth_cmd = /usr/bin/xauth
xsessions = /usr/share/xsessions
```

```bash
#~/.xinitrc
#!/usr/bin/env /bin/sh
/etc/dwm/autostart
```

```bash
#/etc/dwm/autostart
#!/usr/bin/env /bin/sh
xrandr --output eDP-1 --mode 1920x1080 --rate 60
brightnessctl s 100%
feh --bg-fill ~/.wallpaper.png &
/etc/dwm/bar.sh &
picom -b
dwm
dunst &
```

**Comment by Cavernosa** [comment]
Did you make your .xinitrc executable?
```# chmod +x ~/.xinitrc```

**Comment by LiveEmily** [comment]
let me fact check this, will get back to you in roughly 5 minutes.

**Comment by LiveEmily** [comment]
Ye that seems to have been the issue, I recently switched to Gentoo so now I'm running into issues not related to your program at all, sorry for my mistake!
Closing for convience sake.
