### ISSUE TITLE
Multiple monitors mirrored but not using full space

### ISSUE THREAD

**Issue by stevensonmt** [fairyglade/ly#415]
I recognize this might not be an `ly` configuration issue, but it does impact `ly`. I have two monitors of different size and resolution. TTYs are mirrored on each display, meaning the same text shows up on both and any interaction is shown on both.  During post the smaller, lower resolution monitor appears to be set as the primary with both BIOS and kernel boot messages showing up full screen on both but not at full resolution on the larger monitor. Shortly before `ly` launches the screen flashes and the larger, higher resolution monitor displays at full resolution but using only the portion of the screen that appears to correspond to the size of the smaller screen.  Once `ly` launches this arrangement continues. Once X11 starts up the displays work independently as expected, but switching to TTYs demonstrates the same weird restriction in size of the display.

Any idea how to have both monitors use the full screen? I don't care as much that they are mirrored, but if there is a way to limit it to a single display that would be even better.

**Comment by AnErrupTion** [comment]
Quick question, what distro are you using?

**Comment by stevensonmt** [comment]
Arch

**Comment by AnErrupTion** [comment]
Right, just as I expected. I'm not sure why this happens and if we could fix it, as I don't think we can really control the TTY.

**Comment by stevensonmt** [comment]
Are there distros that this does not happen on.

**Comment by brunicius** [comment]
Hello from the future. I'm using Ubuntu 22.04 and i have the same problem.

**Comment by AnErrupTion** [comment]
Closing this issue in favor of #486 which contains more clues and has been more active.
