### ISSUE TITLE
Ly on ARM64 doesn't detect any session other than shell and xinitrc

### ISSUE THREAD

**Issue by marco-04** [fairyglade/ly#417]
I compiled ly both on Arch and Debian (testing) ARM64 VMs, and contrarily to other display managers, like gdm, it didn't detect the session files residing in the "/usr/share/xsessions" directory. I tried with both Gnome and XFCE

**Comment by Cavernosa** [comment]
Try using this version: https://github.com/fairyglade/ly/tree/da5b08abf28970db46ceaf95cd5bda48152799b1
I'm having the same issue after updating to the latest git version, some commit after da5b08a must have broken it.

**Comment by marco-04** [comment]
Yeah, I have the same problem on Asahi Linux with a recursive clone

**Comment by marco-04** [comment]
I probably did when I first tried it, but I can't confirm because now I can't even launch it anymore on Asahi, as it just crashes

**Comment by AnErrupTion** [comment]
Ah, could you try now please? There was a *slight* mistake in the repo that's now fixed :D @marco-04

**Comment by marco-04** [comment]
Just tried, and it doesn't work unfortunately. The same thing happens also for wayland sessions with those options uncommented from the /etc/ly/config.ini file

**Comment by PaddiM8** [comment]
I'm experiencing the same thing, on aarch64

**Comment by PaddiM8** [comment]
I experimented a bit and managed to get it to retrieve the sessions. Not sure if it breaks anything else, but... I added the following in `configator.c` in the configator submodule:

```
if (disc < 0) {
    i = 0;
}
```
on line 45.

The data seems to be retrieved correctly, but the configator search function doesn't end up *only* looking at index 1 when the length is 2. I don't know if this is a good fix, it just happened to make it work for me. I have never really used C.

**Comment by lucidph3nx** [comment]
I can confirm that the solution by @PaddiM8 works with Asahi on M1 Mac booting a sway wayland session.

**Comment by mellowgeekcc** [comment]
Yes, the solution also works on Raspberry 4 booting Xorg sessions.

**Comment by praxis88** [comment]
can confirm this works on arch/manjaro arm

**Comment by AnErrupTion** [comment]
I'm marking this issue as fixed for the Zig rewrite, since it doesn't use configator anymore.
