### ISSUE TITLE
ly fatal error security/pam_app1.h no such file or dir

### ISSUE THREAD

**Issue by tokisuno** [fairyglade/ly#420]
can't make ly
![image](https://user-images.githubusercontent.com/85533116/183471973-75c06381-d405-4908-9614-7d4a01a4990f.png)

**Comment by Cavernosa** [comment]
Elaborate. Literally the first result when googling "fedora pam_appl.h" tells to install `pam-devel` which contains the mentioned file [pam_appl.h](https://packages.fedoraproject.org/pkgs/pam/pam-devel/fedora-36.html#files), have you tried that?

**Comment by AnErrupTion** [comment]
This is a dependency issue, not a Ly issue. Closing.
