### ISSUE TITLE
ly crash on artix w/ s6

### ISSUE THREAD

**Issue by thinkoid** [fairyglade/ly#421]
I am tinkering with running `ly` with `s6/s6-rc` on artix. When I attempt to run l through the `s6-rc` script it crashes because `tb_init` fails to open `/dev/tty`, leaving the functions tables in `termbox` uninitialized and the program crashes upon touching that data. A simple test around the invocation of `tb_init` in `main` would suffice to avoid a segfault.

The underlying problem remains, i.e., why `tb_init` cannot open `/dev/tty`. I am confused about it and I don't think I understand what ly's expectations are in terms of what tty's run under `getty`, etc. At the moment, my system runs with 7 consoles (7 instances of `getty`) from tty1 to tty7. IIUC, `/dev/tty` is the console of the current process ... and the `s6-supervise` process that spawns `ly` when the service is up-ed has no tty attached, which explains why `/dev/tty` cannot be opened? How does or how should this work? I expected that as soon as the service is launched I would be greeted by the ly interface in ... tty1? Is that correct? Or tty2? Any help is greatly appreciated, thanks.

**Comment by Cavernosa** [comment]
Sorry if i misunderstood, but I think you need to set the tty in the init script. It's how it's done in the [systemd script](https://github.com/fairyglade/ly/blob/master/res/ly.service)

**Comment by thinkoid** [comment]
> Sorry if i misunderstand, but I think you need to set the tty in the init script. It's how it's done in the [systemd script](https://github.com/fairyglade/ly/blob/master/res/ly.service)

From my reading of the source code I think what you are referring to is the TTYPath variable there, set to /dev/tty2? I am not sure about the meaning of those variables as they probably refer to how systemd prepares to run ly.

My reading of the code is that the initialization of termbox library (tb_init) is done by using /dev/tty (which translates to the tty of the current process, i.e., the process that spawns/launches ly). This /dev/tty string is hardcoded in the source. Also, the peculiarity of s6 makes that the launching process, s6-supervise, has no tty. So, this fails to initialize termbox and is the source of the segfault described initially.

Even if I change /dev/tty to an existing tty, like /dev/tty1 or /dev/tty3, it still fails because the code it further assumes that the envar TERM is defined which, by default, is not defined in the environ for the launching s6-supervise process. Now, I could hardcode all these but that is not really how it should run, is it?

So, what are ly's expectations? So far I gather that /dev/tty should resolve to the tty of the launching process. That TERM should be in the environ of the launching process. It seems, but is not 100% clear how, that tty2 plays an important role (have not read the whole thing). Is tty2 the tty where the login is displayed? So, is one expectation that no console text login should run there? 

If anyone could shed some light here it would be greatly appreciated. Like what is the mechanism by which it works? And please someone remove that RTFM because the manual is barely worth that name.

**Comment by Cavernosa** [comment]
Hmm, are you calling `agetty`? It sets the TERM, VT and TTY and what to use as login prompt. The systemd's `StandardInput` and `TTYPath` are probably calling agetty or something similar (but i'm not sure). 
It was the only thing that worked for my openrc script, and IIRC there was a runit script that used agetty too.

>It seems, but is not 100% clear how, that tty2 plays an important role (have not read the whole thing). Is tty2 the tty where the login is displayed?

If you mean the `tty` config option which defaults to tty2, all it does, *from what i can see by running ly*, is that 
1. it teleports you to the chosen `tty` when ly is spawned by the init, and 
2. spawns the desktop environment in the chosen `tty`. 

So ly itself can still spawn elsewhere, since it's the init script that's choosing which tty to spawn ly

>And please someone remove that RTFM because the manual is barely worth that name.

It was removed some months ago :raised_eyebrow:

**Comment by thinkoid** [comment]
> Hmm, are you calling `agetty`? It sets the TERM, VT and TTY and what to use as login prompt. The systemd's `StandardInput` and `TTYPath` are probably calling agetty or something similar (but i'm not sure). It was the only thing that worked for my openrc script, and IIRC there was a runit script that used agetty too.

Alright, I took a detour through systemd's manual and reference. `StandardInput` controls where file descriptor 0 (STDIN, input) of the executed processes is connected to. In this case something configured as a tty. And is accompanied by the other variable, `TTYPath`, which tells which one, in this case `/dev/tty2`. IOW, `ly` is launched connected with its input to `/dev/tty2`.

But the definition of ly service under systemd lists getty service (on tty2) as a dependency of ly, so ... is getty already running on tty2? I guess so, that is how I interpret this.

Then I looked at artix runit support for ly. It does something slightly different. It runs agetty on tty2, using ly as a login program, all in one invocation, kinda like this:

`exec agetty -L -8 -n -l /usr/bin/ly tty2 115200 linux`

The above runs agetty, with no login, then sets login program to ly, on tty2, with getty parameters following. So, it seems that I should run it like this, as the login program for agetty.

Initial testing is promising but I stumbled on another crash, unguarded calls to setenv using null pointers.

**Comment by thinkoid** [comment]
FWIW, my progress is lately blocked at the point where ly starts (by agetty) in /dev/tty and I can use it fine to launch a shell. However, when I use it to launch a WM (tested with both dwm and awesome) via xinitrc it runs for a few seconds, after which the cursor and the keyboard both freeze. IOW, no input is processed anymore and I cannot exit the WM nor switch to a console. I must ssh into the box and bring ly down, after which everything unfreezes.

**Comment by Cavernosa** [comment]
> FWIW, my progress is lately blocked at the point where ly starts (by agetty) in /dev/tty and I can use it fine to launch a shell. However, when I use it to launch a WM (tested with both dwm and awesome) via xinitrc it runs for a few seconds, after which the cursor and the keyboard both freeze. IOW, no input is processed anymore and I cannot exit the WM nor switch to a console. I must ssh into the box and bring ly down, after which everything unfreezes.

That's probably loginctl ending your session or something similar happening
I have the same freezing issue when logging out then logging in immediately, and it's because loginctl takes 30 seconds to end my session, so it closes with me logged in and the only way out is pulling the power cable (or as you said ssh).

**Comment by thinkoid** [comment]
> FWIW, my progress is lately blocked at the point where ly starts ...  runs for a few seconds, after which the cursor and the keyboard both freeze.

Which does not happen after I switched my shell from zsh to bash. I might dig up some more into it, but at this point I call it "works for me" and I am stashing the s6 scripts in my [ly-s6 repo](https://github.com/thinkoid/ly-s6). HTH.

**Comment by AnErrupTion** [comment]
Implemented in master, closing. The PR also didn't mention any freezing, so I'm assuming that's fixed!
