### ISSUE TITLE
pam transaction aborted

### ISSUE THREAD

**Issue by hownioni** [fairyglade/ly#427]
Everything worked fine yesterday, I went to sleep and when I boot up the PC again and try to log in with ly on the xinitrc option I'm met with this: https://github.com/fairyglade/ly/issues/2
I've symlinked "/usr/lib/security/pam_loginuid.so" to "/usr/lib/pam_loginuid.so as nullgemm mentioned but it didn't do much. I don't know how to check if ly can access pam_loginuid.so or how to check my pam config or modules. I'm pretty sure I've done no edits to it whatosever.

When trying to log in with the shell option I can actually access my system, but startx is not working either. I'll add that nitrogen does start and load up my wallpaper before the Xorg server is killed, I'm using picom as my compositor and qtile as my window manager.

I'm starting my programs in this order:
```
nitrogen --restore &  
dunst &  
udiskie -s &  
picom &  
wal -R &  
exec qtile start
```

**Comment by hownioni** [comment]
It was a problem with some python libraries I deleted by accident while trying to delete some other package with pip.

**Comment by mysteryjeans** [comment]
Fresh installation of Arch with i3 on Rog M16 2022 getting pam transaction aborted

However able to login with xinit
