### ISSUE TITLE
Black screen on Fedora 36

### ISSUE THREAD

**Issue by madjxatw** [fairyglade/ly#433]
I had ly installed on a Fedora 36 machine but got a black screen with the flickering underscore. Executing `sudo ly` on the text console has no problem. It may have the same cause as #211 but I have no idea how to fix a potential SELinux issue with display manager.  Please advice if anybody has managed to fix this, and waiting for some progress of #310

**Comment by madjxatw** [comment]
After executing the following commands and now I've managed to login.
```
ausearch -c 'ly' --raw | audit2allow -M my-ly
semodule -X 300 -i my-ly.pp
```
But there are still two major issues:

- The first attempt of login (pressing Enter after password typed) always results in logout, and the second attempt succeeds.
- `systemctl restart ly.service` does not work , the login interface doesn't show on tty2.

**Comment by GeorgeBroughton** [comment]
I'm having this problem too.
running as root will at least get me to a shell, but if i try starting sway for example, it's a no-go regardless of whether it runs as root, or whether or not i add an exception for it in SELinux.

On further inspection, i added some lines to my bashrc file to try debugging the situation.

/home/user/.bashrc
```bash
sway -d >/var/log/sway.log 2>&1
```
/var/log/sway.log
```
XDG_RUNTIME_DIR is not set in the environment. Aborting.
```

So, for shiggles, i exported the variable it wanted in my bashrc file:
/home/user/.bashrc
```bash
export XDG_RUNTIME_DIR='/run/user/1000'
sway -d >/var/log/sway.log 2>&1
```
worked that time!

**Comment by umop3plsdn** [comment]
i noticed the change that added $XDG_RUNTIME_DIR for ly but what actually creates that folder /run/user/$UID because i have to manually mkdir and chown it for my non root user

**Comment by jagjordi** [comment]
I still have this problem in Fedora 37, using the latest master branch. Could some one help me troubleshooto it?

**Comment by Cavernosa** [comment]
> i noticed the change that added $XDG_RUNTIME_DIR for ly but what actually creates that folder /run/user/$UID because i have to manually mkdir and chown it for my non root user

(e)logind. From the pam module.

**Comment by jlucier** [comment]
same issue here
