### ISSUE TITLE
Oh no UwU

### ISSUE THREAD

**Issue by MikuChan03** [fairyglade/ly#435]
Hello evewynyan 🎶🎶

This is the solution fow #434 
Watashi was also bothewed by the fact that I couldn't log in any longew, so watashi did some weseawch and found:
```c
int name_len = stwlen(name);
chaw* name_simple = malloc(name_len);

memcpy(name_simple, name, name_len);
```
In inputs.c

This doesn't wowk though, because stwlen doesn't count the twailing null, so this is all scwewy dewey.
name_simple isn't being tewminated O.O
Howevew, if we use the intended stwdup:
```c
int name_len = stwlen(name);
chaw* name_simple = stwdup(name);
```
It all wowks out nicely. It's a mowe stweamylined, kawaii, supew-dupew funcy-wunc.
This is my humble onegai. @AnErrupTion 

Bye bye
💕 xoxo 💕

**Comment by GanerCodes** [comment]
What, precisely, mentally caused this?

**Comment by jrcharney** [comment]
> What, precisely, mentally caused this?

Crushing loneliness and isolation. ;_;

**Comment by GanerCodes** [comment]
You should stop isolating yourself in that case. Clean your room, touch
glass, see a therapist, work on yourself and improve

**Comment by jrcharney** [comment]
> You should stop isolating yourself in that case. Clean your room, touch glass, see a therapist, work on yourself and improve

Whoa! I wasn't talking about myself. Dang. This convo is just too meta to begin with, what with that person being kind of a weeb.

Can we even say that this is a `ly` issue in the first place since clearly OP's act is messing with the code. (It's one thing to have this rhotacism as part of your anime waifu persona, it's another to do it as part of the code sample replacing most of the "r"s with "w"s.

**Comment by jrcharney** [comment]
> oh wait, my dumbass thought you were the same person for some reason lol, it sounded like a personal reply xd

It's OK. Apology accepted.

I'm kinda into anime too, but not to the extent where I act as weird as that person. I do have a day job.

**Comment by MikuChan03** [comment]
Don't wowwy @jrcharney kun, this is weal code in ly that's causing failuwe when loggin in. Honto!

**Comment by AnErrupTion** [comment]
This was funny but also painful to read.

**Comment by MikuChan03** [comment]
Did it wowk? @AnErrupTion 
(Notice me senpai 😖)

**Comment by AnErrupTion** [comment]
Note that, for some reason, I was not getting any segfault even before. I'm going to integrate this code soon, I guess.

**Comment by MikuChan03** [comment]
@AnErrupTion 
Anytime soon???

**Comment by ardishco-the-great** [comment]
I just saw this thread and now I want to kms.

**Comment by imhemish** [comment]
This thread might become popular soon enough.

**Comment by ardishco-the-great** [comment]
I'll send this to a voice actor from youtube to voice act lmao

**Comment by shivanshsharma8834** [comment]
Mentally reading it with a dude's voice. 💀

**Comment by KieranCrossland** [comment]
UwU

**Comment by 10leej** [comment]
> I'll send this to a voice actor from youtube to voice act in a video lmao, also this miku guy talks like this all the time.
> 
> see here : https://github.com/search?utf8=%E2%9C%93&q=commenter%3AMikuChan03&type=issues

Yep made it to YouTube

https://youtu.be/iQsLBb15Xrw

**Comment by AnErrupTion** [comment]
> > I'll send this to a voice actor from youtube to voice act in a video lmao, also this miku guy talks like this all the time.
> > see here : https://github.com/search?utf8=%E2%9C%93&q=commenter%3AMikuChan03&type=issues
> 
> Yep made it to YouTube
> 
> https://youtu.be/iQsLBb15Xrw

🤣

**Comment by CozyMeli-gitv2** [comment]
beautiful

**Comment by WilliamAnimate** [comment]
absolutely amazing github issue right here 👍

**Comment by natsume-shokogami** [comment]
Did anyone come here because of Brodie Robertson?

**Comment by Lavishq** [comment]
> Did anyone come here because of Brodie Robertson?

gm

**Comment by AASonar** [comment]
beautiful

**Comment by rollerozxa** [comment]
> > What, precisely, mentally caused this?
> 
> Crushing loneliness and isolation.

no way that's me

**Comment by ardishco-the-great** [comment]
> Did anyone come here because of Brodie Robertson?

No, but I saw myself in the video! HAHA!
![image](https://github.com/fairyglade/ly/assets/109692107/23965962-c530-41c3-9b6e-dfb88dac6304)

**Comment by SofaSoldierZV** [comment]
for fuck sake, get some testosteron man :O

**Comment by jakiki6** [comment]
uwu

**Comment by jrcharney** [comment]
> > > What, precisely, mentally caused this?
> > 
> > 
> > Crushing loneliness and isolation.
> 
> no way that's me 🥺

**Honestly, if I'm going to be part of some weird video, I should at least get paid for it.**

BTW, I was quite serious about "Crushing loneliness and isolation". 

Sure there's some deadpan sarcasm in that statement, and I too have been in a similar situation, but I didn't start "uwu-fying" my text or go into what I guess is some kind of "femboy-anime" territory (not that there's anything wrong with that).

But seriously, I'm on Github to write code, contribute to issues, and network with my local geeks.

I think this issue has put derailed by the spectacle  of one user, and the sensationalism by another user/YouTuber. 

I was hoping to be seen by a bunch of professional software developers for my own code contributions, not for the antics of some YT video about some guy feeling uncomfortable about "uwu" text in a comment.

**Comment by AnErrupTion** [comment]
@jrcharney So humor is now officially forbidden and banned on GitHub, alright...

**Comment by jrcharney** [comment]
> @jrcharney So humor is now officially forbidden and banned on GitHub, alright...

Not necessarily. I didn't say "I felt embarrassed by that video". If anything, maybe getting noticed in part of that video might be a draw for someone looking for someone with some dry wit to counterbalance absurdity.

After all, Brodie did point out that @MikuChan03 has been actively productive and helpful despite Miku's unconventional and eccentric behavior.

If that's the case, then I'll take whatever secondary exposure I can get.

**Comment by jrcharney** [comment]
@MikuChan03 before this issue explodes any further, I want to congratulate you on your recognition in the Github community.

I'm usually used to working with people a bit more reserved on projects. It's been an honor to make you acquaintance.

**Comment by Heraclito-Q-Saldanha** [comment]
UwU

**Comment by ardishco-the-great** [comment]
> > > > What, precisely, mentally caused this?
> > > 
> > > 
> > > Crushing loneliness and isolation.
> > 
> > 
> > no way that's me pleading_face
> 
> **Honestly, if I'm going to be part of some weird video, I should at least get paid for it.**
> 
> BTW, I was quite serious about "Crushing loneliness and isolation".
> 
> Sure there's some deadpan sarcasm in that statement, and I too have been in a similar situation, but I didn't start "uwu-fying" my text or go into what I guess is some kind of "femboy-anime" territory (not that there's anything wrong with that).
> 
> But seriously, I'm on Github to write code, contribute to issues, and network with my local geeks.
> 
> I think this issue has put derailed by the spectacle of one user, and the sensationalism by another user/YouTuber.
> 
> I was hoping to be seen by a bunch of professional software developers for my own code contributions, not for the antics of some YT video about some guy feeling uncomfortable about "uwu" text in a comment.

I don't mean to be rude, but isn't this the wrong place for this?

**Comment by Chizaruu** [comment]
`De-UWU this text and make it more formal` - Credits ChatGPT

Hello everyone,

I would like to present the solution for issue #434. I encountered a problem where I was unable to log in, so I conducted some research and discovered the following code snippet:

int name_len = strlen(name);
char* name_simple = malloc(name_len);

memcpy(name_simple, name, name_len);


This approach, however, does not work as intended because the strlen function does not include the trailing null character, resulting in incorrect behavior. The variable name_simple is not properly terminated. However, if we utilize the intended function strdup instead, the issue is resolved:

int name_len = strlen(name);
char* name_simple = strdup(name);


This modification ensures the code functions correctly. It is a more streamlined and reliable solution. This is my humble suggestion. "@" AnErrupTion

Thank you and goodbye.

**Comment by AvicennaJr** [comment]
Tears in my eyes 😭😭

**Comment by searinminecraft** [comment]
lol, i wonder why this conversation isnt locked lol

anyway:

OwO nya~

**Comment by s0mt0chukwu** [comment]
@((

**Comment by peachey2k2** [comment]
include me in the screenshot

**Comment by s0mt0chukwu** [comment]
> include me in the screenshot

Go back in time and include yourself

**Comment by medilies** [comment]
Hi. I just wanna be included in future videos.

**Comment by medilies** [comment]
(づ๑•ᴗ•๑)づ just wanna be part of history.

**Comment by arthurkoch** [comment]
uwu

**Comment by medilies** [comment]
UwU

**Comment by babylard** [comment]
Why is this a thing.

**Comment by m-rphy** [comment]
UwU

**Comment by bradenhirschi** [comment]
UwU

**Comment by wahaj4311** [comment]
UWU

**Comment by amirfaisalz** [comment]
uwu ~

**Comment by youtyay** [comment]
uwu

**Comment by zaapr0x** [comment]
UwU
