### ISSUE TITLE
Ly can't launch

### ISSUE THREAD

**Issue by agoodfellow123** [fairyglade/ly#437]
Hello there, I installed ly, disabled sddm.service, and enabled ly.service but sadly it just can not launch. It just sends me to tty1 at start and in tty1 I only see my shell login prompt. When I switch to tty2 it gives me a blank screen with a blinking cursor. When I try to launch ly from tty1 nothing happens I also only see a blinking cursor there. I'm on manjaro with everything up to date, I tried to compile it myself and got the same result, I also tried ly, ly-git and ly-reloaded-git from aur with same result everytime.

**Comment by MikuChan03** [comment]
Don't wowwy, my dude.
#435 takes cawe of this, they just haven't wead it T_T

**Comment by agoodfellow123** [comment]
*Notices your message* OwO soweone elws had the iwssue watashi had? Sowwy watashi waws late. Hopwoolly they fix it soown. Biwg fan btw Miku Chan! Kawaii! (´｡• ω •｡`)

**Comment by MikuChan03** [comment]
Bye the way...
Did you make suwe that
/lib/systemd/system/ly.sewvice and
/etc/ly/config.ini

agwee on which tty is to be used???
Also, since the newest update, the sewvice is no longew installed by default, so you should install it with:
```
sudo make installsystemd
```
Hope this helps, UwU

**Comment by agoodfellow123** [comment]
OwO! The sewvice dowsen't iwnstall by itsew? That miwt be it! Thank anata Miku Chan, watashi will chewk that!

**Comment by osevan** [comment]
I have same Problem. 

My ly.service inside i changed to tty1

And in config.ini i removed # and changed fr tty2 to tty1

Ly login sometimes appears sometimes
![IMG_20220912_004231](https://user-images.githubusercontent.com/77795961/189552972-83e27f2f-1206-474b-b69b-a3533a97a825.jpg)
 not,  but when appears, i cant login.  Error messages. .. #

**Comment by AnErrupTion** [comment]
@osevan Could you please compile from master and see if it works now?

**Comment by AnErrupTion** [comment]
Considering the issue from OP is most likely fixed, I'm closing this issue as solved. @osevan Feel free to open a new issue if your problem persists.
