### ISSUE TITLE
Make on Alpine Linux Edge fails immediately.

### ISSUE THREAD

**Issue by cynicsketch** [fairyglade/ly#440]
As the title says.

Terminal output below. Pulled the source by running` git clone --recurse-submodules https://github.com/fairyglade/ly`, as I read in the instructions.
```
:/home/cysk$ cd gitshit/ly
:/home/cysk/gitshit/ly$ make
building object obj/src/draw.o
src/draw.c:22:18: fatal error: linux/kd.h: No such file or directory
   22 |         #include <linux/kd.h>
      |                  ^~~~~~~~~~~~
compilation terminated.
make: *** [makefile:52: obj/src/draw.o] Error 1
:/home/cysk/gitshit/ly$ 

```

**Comment by AnErrupTion** [comment]
@cynicsketch I think that's a kernel header file. Do you have them installed?

**Comment by Noah-Arcouette** [comment]
installing `linux-headers` seems to fix this issue
