### ISSUE TITLE
ly starts login-sessions as root instead of as the user who logged in

### ISSUE THREAD

**Issue by andornaut** [fairyglade/ly#443]
Recent versions of ly (after 86d0353) start login-sessions as root instead of as the user who logged in.

I noticed this issue, because it broke rootless Xorg, which I initially worked around by adding `needs_root_rights=yes` to `/etc/X11/Xwrapper.config`, and it also prevents a `--user` session of systemd from starting, etc.

One way to validate this is by logging in via ly and then running `loginctl list-sessions` which should show a session for the logged in user (when working), but shows a session for "root" instead (when bugged).

I've since reverted to v0.5.3 which avoids this issue and I've reverted any workarounds I had applied in the interim.

### Environment:

**Distribution**: Ubuntu 22.04
**Window manager**: [bspwm](https://github.com/baskerville/bspwm)
**Dotfiles**: [andornaut/dotfiles](https://github.com/andornaut/dotfiles)

I [install ly using Ansible](https://github.com/andornaut/ansible-workstation/blob/master/roles/desktop/tasks/ly.yml).

---

**Edit:** I've since bisected the commit history:

fairyglade/ly@86d035346e97878bd100f1e286479f4922370aa0 is the last commit that works for me.

fairyglade/ly@09ee6293bdc38d40c210d6f0bd5f811f99329086 is the first commit that exhibits the above issue.

**Comment by rlopzc** [comment]
I had this same issue. Pipewire couldn't start and all XDG variables weren't set.

Reverting to this commit https://github.com/fairyglade/ly/commit/86d035346e97878bd100f1e286479f4922370aa0 as @andornaut specified fixed the issue. Thanks!

**Comment by AnyTimeTraveler** [comment]
Thanks @andornaut for bisecting!
It pointed me directly to the problematic commit.
If you have time, could you test if my fork #446 fixes your issue as well?

**Comment by andornaut** [comment]
@AnyTimeTraveler I tried your fork, but it results in a different error when starting Xorg. I don't recall verbatim, but IIRC it couldn't read or write to `/run/user/1000/lyauth`

That [filepath is derived here](https://github.com/fairyglade/ly/blob/59aae77f492d27c5772944262c84323b6759ae28/src/login.c#L306). The file does exist now that I've logged in with a working version of (86d035346e97878bd100f1e286479f4922370aa0).
```
$ stat /run/user/1000/lyxauth
  File: /run/user/1000/lyxauth
  Size: 49              Blocks: 8          IO Block: 4096   regular file
Device: 53h/83d Inode: 80          Links: 1
Access: (0600/-rw-------)  Uid: ( 1000/andornaut)   Gid: ( 1000/andornaut)
Access: 2022-09-28 18:56:05.845371337 -0400
Modify: 2022-09-28 18:56:05.837371337 -0400
Change: 2022-09-28 18:56:05.837371337 -0400
 Birth: -
```
I've reverted to 86d035346e97878bd100f1e286479f4922370aa0.
