### ISSUE TITLE
ly.service doesn't exist

### ISSUE THREAD

**Issue by abdoulayegk** [fairyglade/ly#452]
Hello i was trying to use this login manager on my arch I installed it from the aur.
I did follow the guidlines from the github as well but nothing is working yet. 
any tips?

**Comment by sloorush** [comment]
Has your install created the default config file at `/etc/ly/config.ini`?

You can check it out by 
```
$ cat /etc/ly/config.ini
```

**Comment by abdoulayegk** [comment]
yes I do have it but it's not working still.

**Comment by AnErrupTion** [comment]
@abdoulayegk This is most likely an issue from the AUR package. By the way, can you try compiling from master branch and following, again, the instructions on the README? (And don't forget to install the service!)

**Comment by AnErrupTion** [comment]
Since there's no further response from OP + Ly is now officially packaged in Arch, I'm closing this issue since it should be resolved.
