### ISSUE TITLE
security/pam_appl.h doesn't exist

### ISSUE THREAD

**Issue by enzocoralc** [fairyglade/ly#454]
I'm installing ly on a fresh install of void linux but when `make` it brings an error saying there's not such file or directory

`src/login.c:13:10: fatal error: security/pam_appl.h: no such file or directory
       13 | #include <security/pam_appl.h>
            |
compilation terminated.
make: *** [makefile:52: obj/src/login.o] Error 1`

**Comment by ganajtur0** [comment]
you have to install the `pam-devel` package on your system `xbps-install -Su pam-devel`

**Comment by enzocoralc** [comment]
okay, thank you.

**Comment by enzocoralc** [comment]
Hello again, after trying again now it says `xcb/xcb.h` does not exist
