### ISSUE TITLE
On OpenRC, trying to shutdown the computer using ly does not shutdown the computer.

### ISSUE THREAD

**Issue by searinminecraft** [fairyglade/ly#463]
When I tried to shutdown my computer using ly, OpenRC switched to a runlevel called 'single', which means 'Single User' and just prompts me for the root password and goes to a root shell, and not shutdown the system. It isn't supposed to use the 'single' runlevel, but rather the 'shutdown' runlevel.

The OS I use is Artix Linux with OpenRC

**Comment by Cavernosa** [comment]
I think you need to change this option in `/etc/ly/config.ini`:
```dosini
# Command executed when pressing F1
#shutdown_cmd = /sbin/shutdown -a now
```
See `man openrc-shutdown`

Btw what are the contents of `/etc/init.d/ly` ?

**Comment by Cavernosa** [comment]
Ok i just tested, you have to change it to the usual `poweroff` command. `openrc-shutdown` doesn't have `-a` option so it fallbacks to single user mode.
```dosini
shutdown_cmd = /sbin/poweroff
```
Or you could just use the `openrc-shutdown` command (which is what the poweroff cmd does):
```dosini
shutdown_cmd = /sbin/openrc-shutdown -p now

**Comment by searinminecraft** [comment]
> Ok i just tested, you have to change it to the usual `poweroff` command. `openrc-shutdown` doesn't have `-a` option so it fallbacks to single user mode.
> 
> ```ini
> shutdown_cmd = /sbin/poweroff
> ```
> 
> Or you could just use the `openrc-shutdown` command (which is what the poweroff cmd does):
> 
> ```ini
> shutdown_cmd = /sbin/openrc-shutdown -p now
> ```

Okay, i changed the settings with those values, and now it shuts down properly! Thanks.
