### ISSUE TITLE
/etc/ly not being created

### ISSUE THREAD

**Issue by lory8** [fairyglade/ly#474]
Hi, I'm trying to install ly in my Ubuntu 20.04 machine but after running 'make install installsystemd' I get the following error:
install: cannot change permissions of '/etc/ly': No such file or directory

Any ideas on why this might be happening?

**Comment by Cavernosa** [comment]
```
$ install -dZ /etc/test/
install: cannot change permissions of ‘/etc/test’: No such file or directory
$ file /etc/test/
/etc/test/: cannot open `/etc/test/' (No such file or directory)

# install -dZ /etc/test/
$ file /etc/test/
/etc/test/: directory
```

Did you run it with root privileges?

**Comment by AnErrupTion** [comment]
As this issue looks resolved and OP hasn't answered, I'm closing this one.
