### ISSUE TITLE
can you make apt-get install not use make

### ISSUE THREAD

**Issue by newyorkthink** [fairyglade/ly#476]
![image](https://user-images.githubusercontent.com/87791643/210599187-8ba68acf-e08f-4f68-8928-b65cbdb3d696.png)

I like aptitude 

i not how to make

**Comment by yum13241** [comment]
That is because the dev did not build binaries for Ubuntu. You have to use `make`. Arch (and derivatives) are lucky to have the `chaotic-AUR`, so we don't have to `make`.

**Comment by AnErrupTion** [comment]
This isn't exactly because we aren't building binaries for Ubuntu, it's because Ly is simply not in the Ubuntu repositories.
