### ISSUE TITLE
Ly disables display-manager-init on Gentoo

### ISSUE THREAD

**Issue by gagero** [fairyglade/ly#481]
I don't know if this is intentional, but a disclaimer in the README would be appreciated.

**Comment by arthurx07** [comment]
It's happened to me as well, ly can't be started through display-manager-init on Gentoo. You have to disable it first, and then enable ly to start in the default runlevel (rc-update add ly).
I also think it'd be great to mention it in the README.

**Comment by arthurx07** [comment]
I didn't know that only some DMs could be used with display-manager-init, thanks for clarifying it. Display-manager not starting automatically should definitely be mentioned in the readme.
