### ISSUE TITLE
how to remove ly from my computer..

### ISSUE THREAD

**Issue by Farhad618** [fairyglade/ly#484]

**Comment by rlopzc** [comment]
Remove the service from startup:
```
systemctl disable ly.service
```

Remove ly from your computer:
```
pacman -Rs ly
```

**Comment by zetaomegagon** [comment]
It depends.
- If you installed with a package manager; then uninstalling with the package manager should take care of everything.
- If you installed from source; then `cd` into the source directory and run (as root) `make uninstall`. If you're curious what it's doing you can open up the `makefile` in a text editor and find the `uninstall` section.
