### ISSUE TITLE
Create a new fied to execute a bash script 

### ISSUE THREAD

**Issue by goodbyeMyFish** [fairyglade/ly#485]
Hello!

Is it possible to create a new field like the one for choosing the window manager, but for executing a specific bash script.

This may really extend the possibilities of ly.

One example: for peoples who have a laptop, this thing can for example help them by running with the dGPU or iGPU using a bash script.

**Comment by AnErrupTion** [comment]
@goodbyeMyFish Hey! For that, you can use the ``~/.xinitrc`` on X11. Alternatively, you can modify the ``/etc/ly/xsetup.sh`` file for X11, and ``/etc/ly/wsetup.sh`` for Wayland.

**Comment by AnErrupTion** [comment]
This is now tracked by #499.
