### ISSUE TITLE
Xsessions options only show "Application" rather than the name of the session

### ISSUE THREAD

**Issue by doqfgc** [fairyglade/ly#489]
The sessions list appears to pull from the "Type=" field for each .desktop in /usr/share/xsessions, rather than the "Name=", resulting in all of the sessions appearing as "Application" instead of the sessions name. It makes ly impossible to use beyond xinitrc and shell, particularly with multiple sessions.

**Comment by AnErrupTion** [comment]
@doqfgc This shouldn't be an issue anymore with the Zig rewrite. Feel free to mention me if that's still the case and I'll reopen the issue.
