### ISSUE TITLE
Vi mode.

### ISSUE THREAD

**Issue by RannyArcher** [fairyglade/ly#491]
the most of **ly** users are probably _vim_ and _emacs_ users so can you make a vi mode for them plz.

`ESC/CTRL_[` for _normal_ mode
`i` for _insert_ mode
`hjkl` for going _up/down/right/left_

lot of us will **love it more** :) plzzzzzzzzzzzz

**Comment by AnErrupTion** [comment]
@RannyArcher Commit faa76def085a01f733cd4d006b663845e88ce660 implements controls for going in different directions. I guess now we need normal/insert mode. I'm not a vi user at all, so, just in case, I'll ask: normal mode means you can look around, and insert mode means you can input text? Is that right?

**Comment by RannyArcher** [comment]
> @RannyArcher Commit [faa76de](https://github.com/fairyglade/ly/commit/faa76def085a01f733cd4d006b663845e88ce660) implements controls for going in different directions. I guess now we need normal/insert mode. I'm not a vi user at all, so, just in case, I'll ask: normal mode means you can look around, and insert mode means you can input text? Is that right?

exactly... i think that would let us even use LY like vim without having to click the Controle key.
and maybe even have the ability to use h,l keyos to navigate the text in entries.
