### ISSUE TITLE
Ly is not reading '/etc/ly/config.ini' on startup

### ISSUE THREAD

**Issue by therealteddy** [fairyglade/ly#497]
Hello! 

# Question 1:- 

- I have installed 'ly' from the AUR, and it works okay. However, any changes I make to the `config.ini` at `/etc/` does'nt get read on startup. 

- If I run ly from terminal like this:
`ly --config /etc/ly/config.ini` 
Then, ly runs my configuration fine!

- Is there a way to get ly to read my config at startup? 

# Question 2:- 
How can I tell ly to read my config at `'$HOME/.config/ly/config.ini` as opposed to the default config (@ `/etc/ly/config.ini`)?

**Comment by Cavernosa** [comment]
Try [ly-git](https://aur.archlinux.org/packages/ly-git) instead to see if it gets fixed.

On your second question: I think you can set the `--config` flag in the systemd service file like this (see `man systemd.service`):
```
ExecStart=/usr/bin/ly --config /home/<name>/.config/ly/config.ini
```
I don't see why you'd want to do that tho since Ly is a login manager

**Comment by therealteddy** [comment]
Hi,
Thank you for your response.
Ly-git fixed it!
I'm sorry for bothering you before trying the git version.
Thank you once again!

**Comment by therealteddy** [comment]
Hi Fairyglade,
Thanks for your response.
I tried git-ly but it didn't fix it.
If I restart ly, however, it seems to load the config.
Thank you once again!

**Comment by Thiago-Assis-T** [comment]
I am havingthe same issue, even tho i'm on ly-git, already disabled and reenabled the service, if inside a session I restart it, it reads the config and works when I logout, however not in a reboot

**Comment by AnErrupTion** [comment]
@Thiago-Assis-T Could you open a separate issue and explain it in greater detail please? Thanks! Closing this issue since it appears to be fixed.
