### ISSUE TITLE
Add support of cyrillic languages. 

### ISSUE THREAD

**Issue by KR1470R** [fairyglade/ly#498]
i've choosed ukrainian language and have this problem. the same problem with other cyrillic languages
![image](https://user-images.githubusercontent.com/54418933/232210145-5120eed0-c839-4aed-95d5-a1a86a4984d2.png)

**Comment by Cavernosa** [comment]
you need a console font that supports cyrillic

**Comment by AnErrupTion** [comment]
As @Cavernosa said, you'll need a console font that supports cyrillic characters. Closing the issue since it's not related to Ly.
