### ISSUE TITLE
Login/logout script option

### ISSUE THREAD

**Issue by Sixene** [fairyglade/ly#499]
I’d like to use ly on my laptop with optimus-manager, but sadly I can’t get it to work properly since ly doesn’t seem to have options for scripts to run on login and logout. Would it be possible to add support for it so I can use optimus-manager? Thanks!

**Comment by ToxyFlog1627** [comment]
Hi, I'm not a dev, but am interested to help you.
What wm/de you use?
What do you mean by scripts on login to run? If you're using X, why not add whatever you need to .xinitrc?

**Comment by Sixene** [comment]
Hey thanks, I use openbox, .xinitrc works for the login script optimus-manager needs to switch, which is great, but it also needs to run a script on logout as sudo to complete the switch, and I can’t find an option to do that in ly or through x, I basically need to run a script when the session ends or after, so on logout.
Thanks for your response!

**Comment by ToxyFlog1627** [comment]
I'm pretty sure you can start by creating small service that will be ran on shutdown.
Take a look at this https://unix.stackexchange.com/questions/39226/how-to-run-a-script-with-systemd-right-before-shutdown
I think I have an idea how to do it. I'll try opening pull request, though it might have some security issues that I don't see.

**Comment by Sixene** [comment]
If this can work for logout then I could try it, the whole point would be to not have to shut down

**Comment by ToxyFlog1627** [comment]
What do you mean by `to not have to shut down`?

**Comment by Sixene** [comment]
No, I need to run a script as root on logout, not shutdown

**Comment by ToxyFlog1627** [comment]
I'm sorry, but what do you mean by logout? Going back to dm after quiting wm?

**Comment by Sixene** [comment]
Yeah, going back to dm after exiting wm, like for example when you press logout in kde

**Comment by ToxyFlog1627** [comment]
Yeah, sorry about that. I misunderstood as I never logout myself.
I think you can do that by adding something like this:
`if (fork() == 0) execl(pwd->pw_shell, pwd->pw_shell, "-c", ABSOLUTE_PATH_TO_YOUR_EXEC_OR_SCRIPT, NULL);`
At line 669 (right before `exit(EXIT_SUCCESS);`) of login.c
It seems to work for me.
Could you try it?

**Comment by ToxyFlog1627** [comment]
It *should* be ran as root as ly is ran as root.
I specified - *src/login.c*

**Comment by Sixene** [comment]
So I need to pull the source of ly, make the edit then build right?

**Comment by ToxyFlog1627** [comment]
Yes. Build instructions are in readme. And of course script path.
I would recommend to start with logging sth in that script in order to ensure it gets executed.

**Comment by Sixene** [comment]
Yeah, sadly it didn’t work, two issues I’m running into is a) ly freezes after logout, it just shows up as normal and says logged out where it usually lets you pick the wm, but it doesn’t take any input. b) see picture attached, i didn’t think the script is getting run as root, my switch settings might be wrong too though
![F10C43D2-CCF7-4780-A711-2AA7C35E4CDF](https://user-images.githubusercontent.com/60512632/233675360-74123b47-5641-4571-8d16-6c06d4f27bb0.jpeg)

**Comment by ToxyFlog1627** [comment]
Okay, try this in the same file (src/logout.c). It fixes root issue, and PROBABLY will fix ly freezing.
Also, just to be sure, it wasn't freezing on logout before, right?
```
if (pid == 0)
{
	pid_t pid = fork();
        if (pid == 0)
        {
            // set user info
            ok = initgroups(pwd->pw_name, pwd->pw_gid);

            if (ok != 0)
            {
                dgn_throw(DGN_USER_INIT);
                exit(EXIT_FAILURE);
            }

            ok = setgid(pwd->pw_gid);

            if (ok != 0)
            {
                dgn_throw(DGN_USER_GID);
                exit(EXIT_FAILURE);
            }

            ok = setuid(pwd->pw_uid);

            if (ok != 0)
            {
                dgn_throw(DGN_USER_UID);
                exit(EXIT_FAILURE);
            }

            // get a display
            char vt[5];
            snprintf(vt, 5, "vt%d", config.tty);

            // set env
            env_init(pwd);

            if (dgn_catch())
            {
                exit(EXIT_FAILURE);
            }

            // add pam variables
            char** env = pam_getenvlist(handle);

            for (uint16_t i = 0; env && env[i]; ++i)
            {
                putenv(env[i]);
            }

            // execute
            int ok = chdir(pwd->pw_dir);

            if (ok != 0)
            {
                dgn_throw(DGN_CHDIR);
                exit(EXIT_FAILURE);
            }

            reset_terminal(pwd);
            switch (desktop->display_server[desktop->cur])
            {
                case DS_WAYLAND:
                {
                    wayland(pwd, desktop->cmd[desktop->cur]);
                    break;
                }
                case DS_SHELL:
                {
                    shell(pwd);
                    break;
                }
                case DS_XINITRC:
                case DS_XORG:
                {
                    xorg(pwd, vt, desktop->cmd[desktop->cur]);
                    break;
                }
            }

	    exit(EXIT_SUCCESS);
        }
        
        waitpid(pid, NULL, 0);
        setsid();
        if (fork() == 0) execl("/bin/sh", "sh", "-c", YOUR_SCRIPT, NULL);
}
```

**Comment by Sixene** [comment]
Sadly i get the same error, same behaviour.
Maybe I have to change switch method, I’ll have to see about that one, but the script still isn’t running as root judging from that error

**Comment by ToxyFlog1627** [comment]
Strange, mine is ran as root.
Maybe you forgot to recompile/reinstall?
Anyway, last thing is how you logout? Is there default option in openbox?

**Comment by ToxyFlog1627** [comment]
` by trying to switch gpus in optimus manager` - maybe that is issue? I have no idea how they do it, so maybe that's why it works for me, but not for you.
Can you log out in other way? (idk how to in openbox)
Maybe that will be better.
If you do, tell me how

**Comment by Sixene** [comment]
Yeah, but my entire issue here is I can’t switch gpus because the script doesn’t run correctly. Anyways, if I log out normally I’m just left with an empty screen, some logs from boot, and the flashing terminal cursor

**Comment by ToxyFlog1627** [comment]
Okay, I found that optimus-manager invokes `openbox --exit`
To be honest, I also have some issues logging out back to ly.
So issue **probably** isn't with the manager, but how ly handles logging out.
It makes it easier to test.
 I'll see what can be done

**Comment by Sixene** [comment]
Thank you! You have been amazing help so far and I really appreciate it

**Comment by Sixene** [comment]
So basically, i need a script to run on logout, and optimus-manager logs me out when i switch gpus. Sorry for taking so long, i’ll be trying your suggestion today, just been busy

**Comment by ToxyFlog1627** [comment]
Why not run this script before logging out? Like right before swirching gpus. Is there something that can't be ran while logged in?

**Comment by Sixene** [comment]
Since it switches the in-use gpu, i presume you can’t run it because it’s in use by x11

**Comment by Sixene** [comment]
Hey, thanks for responding, I kinda gave up hope, yeah I’m using the solution in the issue you linked, my problem still remains with the other script meant to be run at logout. :(

**Comment by AnErrupTion** [comment]
@Sixene Hey! I think we should add a feature to run a script when logging out. This *should* in theory be possible since Ly can detect when the user logged out. How does that sound?

**Comment by Sixene** [comment]
Sounds great! I’d love to help in testing it. Thanks for your response!

**Comment by LnLcFlx** [comment]
I also notice this issue after logging out of bspwm.
When logging in again the session works until the dGPU goes to sleep, then it crashes.

Any progress on this?

**Comment by AnErrupTion** [comment]
This feature will probably be added for Ly v1.1.0. Sorry for the wait but it should be sooner rather than later now.

**Comment by Xefreh** [comment]
any updates ? I think a lot of people need it.

**Comment by AnErrupTion** [comment]
It's now implemented in master. Sorry for the wait! :v

**Comment by AxelHumeau** [comment]
So how do we configure it now ?

**Comment by AnErrupTion** [comment]
> So how do we configure it now ?

You have to set `login_cmd` and/or `logout_cmd` in the config file. Check [this](https://github.com/fairyglade/ly/blob/022d146f76a1e87418bf15fed5909b2978b79f6a/res/config.ini#L134) out for the syntax.
