### ISSUE TITLE
can i install ly with .xprofile?

### ISSUE THREAD

**Issue by ursuloc** [fairyglade/ly#502]
I am trying to install ly in bspwm but I have already tried with .xprofile and with xinitrc and when I run and put my password it sends me to the console and tells me

`/usr/bin/xauth no such file or directory`
`/usr/bin/x no such file or directory`

**Comment by AnErrupTion** [comment]
@ursuloc Perhaps you don't have X11 installed? Check first if you have xauth installed using your distribution's package manager. (Usually, the package is named xauth for, well, xauth.)

**Comment by AnErrupTion** [comment]
Since this doesn't seem to be an Ly issue + no response from OP, I'm closing this issue.
