### ISSUE TITLE
Ly runs but does not work if session directories contain subdirectories

### ISSUE THREAD

**Issue by wizetek** [fairyglade/ly#506]
**Steps to reproduce**
1.
`# mkdir /usr/share/xsessions/foo`
or
`# mkdir /usr/share/wayland-sessions/bar`
2. (Re)start ly.service
3. Check  status
```
# pgrep -a ^ly
306 /usr/bin/ly-dm

# systemctl status ly.service
...
Active: active (running)
...
```
###### Arch Linux x86_64<br>ly 0.5.3

**Comment by h45h74x** [comment]
Yep, got this bug too. Spent almost an hour wondering why `ly-dm` was using 100% on one CPU core, whilst not loading and throwing me into TTY1 initially. Removing all subdirectories in `/usr/share/xsessions` and restarting ly fixed the issue.
