### ISSUE TITLE
Not working on Debian 12 without Systemd

### ISSUE THREAD

**Issue by jr20xx** [fairyglade/ly#511]

**Comment by AnErrupTion** [comment]
@jr20xx Could you be more specific, please? What doesn't work exactly?

**Comment by jr20xx** [comment]
> @jr20xx Could you be more specific, please? What doesn't work exactly?

I was able to do everything and build Ly; but then, when it is suposed to start, it never does it. I even removed my display manager but it just never starts. I never get to see the login screen. I tested it on Debian 12 with Sysvinit and runit and it didn't work as expected in any of them. It doesn't show me the login screen and I always have to reinstall lightdm to see a login screen again

**Comment by yutent** [comment]
It works well here.

my os info:

OS: debian bookworm & sid
DE: xfce4 & cinnamon
Kernel: 6.1.27 & 6.3.7

**Comment by jr20xx** [comment]
> @jr20xx 
> 
> It works well here.
> 
> my os info:
> 
> OS: debian bookworm & sid
> DE: xfce4 & cinnamon
> Kernel: 6.1.27 & 6.3.7
> 
> you can try to download this: https://repo.izero.im/pool/main/l/ly/ly_0.6.0_amd64.deb

Thanks for the link... but first: does the system where you are testing that package don't use systemd as init?

**Comment by yutent** [comment]
> Thanks for the link... but first: does the system where you are testing that package don't use systemd as init?

Of course, I use Systemd, and I am using the official Debian operating system. Both of my computers are Debian systems, but one of them is using Debian sid。

**Comment by jr20xx** [comment]
> > Thanks for the link... but first: does the system where you are testing that package don't use systemd as init?
> 
> Of course, I use Systemd, and I am using the official Debian operating system. Both of my computers are Debian systems, but one of them is using Debian sid。

Then you are not in the same situation that I'm describing and that I need help with

**Comment by yutent** [comment]
You can try this below.

```
# /etc/init.d/ly

### BEGIN INIT INFO
# Provides:          tui-display-manager
# Required-Start:    $local_fs $remote_fs $syslog
# Required-Stop:     $local_fs $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: TUI display manager
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
DAEMON=/usr/bin/ly
NAME=tui-display-manager
DESC="TUI display manager"

test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting $DESC"
    start-stop-daemon --start --quiet --exec $DAEMON --background -- \
      --no-kernel-messages --tty=/dev/tty2
    log_end_msg $?
    ;;
  stop)
    log_daemon_msg "Stopping $DESC"
    start-stop-daemon --stop --quiet --oknodo --retry=TERM/30/KILL/5 \
      --exec $DAEMON
    log_end_msg $?
    ;;
  restart|force-reload)
    log_daemon_msg "Restarting $DESC"
    start-stop-daemon --stop --quiet --oknodo --retry=TERM/30/KILL/5 \
      --exec $DAEMON
    start-stop-daemon --start --quiet --exec $DAEMON --background -- \
      --no-kernel-messages --tty=/dev/tty2
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
```

**Comment by jr20xx** [comment]
> You can try this below.
> 
> ```
> # /etc/init.d/ly
> 
> ### BEGIN INIT INFO
> # Provides:          tui-display-manager
> # Required-Start:    $local_fs $remote_fs $syslog
> # Required-Stop:     $local_fs $remote_fs $syslog
> # Default-Start:     2 3 4 5
> # Default-Stop:
> # Short-Description: TUI display manager
> ### END INIT INFO
> 
> PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
> DAEMON=/usr/bin/ly
> NAME=tui-display-manager
> DESC="TUI display manager"
> 
> test -x $DAEMON || exit 0
> 
> set -e
> 
> . /lib/lsb/init-functions
> 
> case "$1" in
>   start)
>     log_daemon_msg "Starting $DESC"
>     start-stop-daemon --start --quiet --exec $DAEMON --background -- \
>       --no-kernel-messages --tty=/dev/tty2
>     log_end_msg $?
>     ;;
>   stop)
>     log_daemon_msg "Stopping $DESC"
>     start-stop-daemon --stop --quiet --oknodo --retry=TERM/30/KILL/5 \
>       --exec $DAEMON
>     log_end_msg $?
>     ;;
>   restart|force-reload)
>     log_daemon_msg "Restarting $DESC"
>     start-stop-daemon --stop --quiet --oknodo --retry=TERM/30/KILL/5 \
>       --exec $DAEMON
>     start-stop-daemon --start --quiet --exec $DAEMON --background -- \
>       --no-kernel-messages --tty=/dev/tty2
>     log_end_msg $?
>     ;;
>   *)
>     echo "Usage: $0 {start|stop|restart|force-reload}" >&2
>     exit 1
>     ;;
> esac
> 
> exit 0
> ```

Thanks! I will give it a try as soon as I can

**Comment by jr20xx** [comment]
> You can try this below.
> 
> ```
> # /etc/init.d/ly
> 
> ### BEGIN INIT INFO
> # Provides:          tui-display-manager
> # Required-Start:    $local_fs $remote_fs $syslog
> # Required-Stop:     $local_fs $remote_fs $syslog
> # Default-Start:     2 3 4 5
> # Default-Stop:
> # Short-Description: TUI display manager
> ### END INIT INFO
> 
> PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
> DAEMON=/usr/bin/ly
> NAME=tui-display-manager
> DESC="TUI display manager"
> 
> test -x $DAEMON || exit 0
> 
> set -e
> 
> . /lib/lsb/init-functions
> 
> case "$1" in
>   start)
>     log_daemon_msg "Starting $DESC"
>     start-stop-daemon --start --quiet --exec $DAEMON --background -- \
>       --no-kernel-messages --tty=/dev/tty2
>     log_end_msg $?
>     ;;
>   stop)
>     log_daemon_msg "Stopping $DESC"
>     start-stop-daemon --stop --quiet --oknodo --retry=TERM/30/KILL/5 \
>       --exec $DAEMON
>     log_end_msg $?
>     ;;
>   restart|force-reload)
>     log_daemon_msg "Restarting $DESC"
>     start-stop-daemon --stop --quiet --oknodo --retry=TERM/30/KILL/5 \
>       --exec $DAEMON
>     start-stop-daemon --start --quiet --exec $DAEMON --background -- \
>       --no-kernel-messages --tty=/dev/tty2
>     log_end_msg $?
>     ;;
>   *)
>     echo "Usage: $0 {start|stop|restart|force-reload}" >&2
>     exit 1
>     ;;
> esac
> 
> exit 0
> ```

Well, thanks. I already tried with the DEB file previously quoted and with the creation of a file containing all that; and none of those stuffs worked
