### ISSUE TITLE
Please add git submodules to tarball

### ISSUE THREAD

**Issue by X1mper** [fairyglade/ly#515]
This would simplify package maintenance in linux distributions

**Comment by X1mper** [comment]
version 0.6.0

**Comment by AnErrupTion** [comment]
@X1mper This is unfortunately not possible (yet): https://github.com/dear-github/dear-github/issues/214

I suggest you instead clone from the last commit for v0.6.0, which is 1c2be475ad09af18e632609c779d508e7fb866f9.

**Comment by X1mper** [comment]
> @X1mper This is unfortunately not possible (yet): [dear-github/dear-github#214](https://github.com/dear-github/dear-github/issues/214)
Okay, it's sad, but I'll think about how I can do it right... I just haven't seen it yet

**Comment by AnErrupTion** [comment]
Also this is a duplicate of #226. :P
