### ISSUE TITLE
Xorg server command seems to be ignored / not being used

### ISSUE THREAD

**Issue by cosmocanyon** [fairyglade/ly#518]
Since last update ly 0.6.0 1 is not possible anymore to re-enable the session log redirection for the rootless xorg.

With the following setting there's no output to Xorg.log but appears on screen:

Xorg server command
x_cmd = /usr/bin/X -keeptty >~/.local/share/xorg/Xorg.log 2>&1

Downgrading to ly 0.5.3 5 it works.

**Comment by embhd** [comment]
I noticed, that according to src/config.c the different options/fields for the config-struct "must be alphabetically sorted", which is currently broken by the entry for xinitrc. Although fixing only that (c.f. 30d9f7a39eb8037371000ee960ae10091db2b88b) doesn't seem to be enough to solve the issue.

**Comment by embhd** [comment]
I found it: the missing piece was commit 42bf929756675f1e6cb922f721665d581574fdc6, which fixes config.map_len size in src/config.c, but came shortly after the release of v0.6.0 - the one I was testing.

**Comment by AnErrupTion** [comment]
@embhd @cosmocanyon So, is it fixed?

**Comment by AnErrupTion** [comment]
I'm assuming that this bug is fixed + no response from both users (their accounts aren't active either...), so I'm closing this issue.

**Comment by LASER-WOLF** [comment]
> I'm assuming that this bug is fixed + no response from both users (their accounts aren't active either...), so I'm closing this issue.

Ah, I don't think this issue is fixed unfortunately. At least as far as I can tell, editing the "x_cmd" option in config.ini has no effect at all :(

**Comment by AnErrupTion** [comment]
@LASER-WOLF What you may be able to do instead is create a shell script that calls `/usr/bin/X` and redirects its output, and modify `config.x_cmd` to call that script instead.
