### ISSUE TITLE
Supprt for xinit alternatives

### ISSUE THREAD

**Issue by TheRedOnline** [fairyglade/ly#523]
I use [sx](https://github.com/Earnestly/sx) in place of startx as its extremely lightweight.  I currently see the option to change the path to the xinitrc, but is there a way to change how or what gets launched?

**Comment by AnErrupTion** [comment]
@TheRedOnline Ly doesn't use startx, it starts X directly. I believe it then reads the xinitrc file. You could modify the xinitrc file directly (by default it's under ``~/.xinitrc``). There's also the xsetup.sh script which sets up some things for you, maybe you could put stuff under there as well.
