### ISSUE TITLE
Empty the password field if the entered password is incorrect or let the user unmask the password.

### ISSUE THREAD

**Issue by jcnafi** [fairyglade/ly#524]
Password is masked when typed. So when a typed password is incorrect there is no way to figure out where. Instead of keeping the password on the field it can be cleared or let the user unmask the password using any keybinding or something.

**Comment by darkclaw96** [comment]
you can clear a wrong password by setting "blank_password = true" in /etc/ly/config.ini

**Comment by jcnafi** [comment]
@darkclaw96 thank you.

**Comment by Alleop5** [comment]
Close this?
