### ISSUE TITLE
Ly starts wrong Window Manager

### ISSUE THREAD

**Issue by izzijaz** [fairyglade/ly#525]
I have Xmonad selected in Ly. When i login, Cinnamon Desktop Environment starts up instead of Xmonad. I am running Mint 21

**Comment by Scary-Guy** [comment]
Sorry this is kinda late and you've likely already solved it, but I'm sticking this here for others.

Under /etc/X11/default-display-manager/ exists a bunch of .desktop files.  It's likely you can just edit it and point it to Xmonad.

**Comment by AnErrupTion** [comment]
Stale issue + can't reproduce, closing.
