### ISSUE TITLE
Close logind session on logout

### ISSUE THREAD

**Issue by ToxyFlog1627** [fairyglade/ly#526]
When I logout of of the WM back to Ly logind session isn't closed for other 10 seconds.
I know that it is setting in the logind.conf or whatever, but why not run something like `loginctl terminate-session self` to closed it right away?
The issue is that if I don't wait for it to end, then it will be closed while I'm in new session. Therefore, it makes system unresponsive, hence I have to force shutdown.
I don't know whether it is issue for runit and OpenRC without elogind, but if it is there should be other commands / ways to do so.

**Comment by AnErrupTion** [comment]
@ToxyFlog1627 Can you check if this issue persists with the latest code in master, please?

**Comment by ToxyFlog1627** [comment]
Sorry, I don't have access to that machine anymore. I could test it on my new Linux install, but I'm away from it too until mid August.

**Comment by ToxyFlog1627** [comment]
@AnErrupTion Sorry it took so long, looks fine to me.
