### ISSUE TITLE
Additional characters from unknown origin

### ISSUE THREAD

**Issue by le-jun** [fairyglade/ly#527]
Using the french locale, some characters appears apparently out of nowhere.  Here's the displayed text (when launched in the terminal) :

![image](https://github.com/fairyglade/ly/assets/88536727/7f335c82-177e-4f65-93fd-c3675183144c)

The text for reboot should be "redémarrer" but for some reason a "t" appears a the end. I've checked the [source strings](https://github.com/fairyglade/ly/blob/2ca870cfc5cd6611bb1fd52dcd67ef40895ad787/res/lang/fr.ini#L41) which seem right.

I'm not sure how to take a screen on the login screen, but on the right of "éteindre" also appear a blue character which, in my understanding, is a Unicode right directed arrow. Weirdly enough, this doesn't show on a terminal output.

**Comment by j3dR** [comment]
I have the same issue with Polish language. When I set to English in ly's config.ini, everything looks fine.
