### ISSUE TITLE
How to pronounce Ly?

### ISSUE THREAD

**Issue by ArvinSKushwaha** [fairyglade/ly#535]
Hi! I'm wondering how exactly one is supposed to pronounce Ly. Is it `lee`, `lie`, or something else entirely? Thanks for your time!

**Comment by developer1105** [comment]
Maybe just like the word lu (meaning read in french), and with a nearly identical phonetics in german (lü).
But a bigger name (with more letters) would make it easier for the project to be located on search engines, at least that is what I guess...

**Comment by RodrigoPrestes** [comment]
Says on the [readme](https://github.com/fairyglade/ly#additional-information) it's a tribute to the fairy in the Rayman games, so I guess it's `lee`.
https://www.youtube.com/watch?v=odQ5HVrAESY&t=15s

**Comment by markstos** [comment]
This issue has been answered and ca nbe closed.
