### ISSUE TITLE
Weird characters on login screen

### ISSUE THREAD

**Issue by ivanduque0** [fairyglade/ly#539]
Does anyone know why my log in box looks like that?, i have been looking for a solution in google but no luck. Hope anyone knows the reason my login box has those characters.

https://ibb.co/28Kgyq0

**Comment by tysongeorge** [comment]
I recently had the same issue, not sure what had caused it; re-building didn't help either. However, I was also having a locale error in within foot-term, and after fixing that (editing `/etc/locale.conf` changing "LANG=C.UTF-8" to "LANG=en_US.UTF-8") my issue was gone after a reboot; hopefully that might help you here.

**Comment by ivanduque0** [comment]
That worked for me, thank you so much!
