### ISSUE TITLE
Add WM DWL

### ISSUE THREAD

**Issue by fireworx** [fairyglade/ly#547]
please add the upcoming WM DWL (wayland successor of DWM)

thanks ;-)

**Comment by denisdubochevalier** [comment]
Hello, I just tested it:

It works with DWL, but you have to change the `waylandsessions` in config.ini to point to `/usr/local/share/wayland-sessions`.

Another solution is to change the `PREFIX` of dwl to `/usr` before running `make install` if you want to have it listed alongside your other wayland sessions.

Finally, you can manually create a symlink to the desktop file in `/usr/share/wayland-sesssions`.
