### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by ghost** [fairyglade/ly#549]
De: Openbox
Init: SysV
I have successfully built the package and tried to use the slim SysV service as a template to create the service. The service segfaults at boot, but even though I start ly from console I always get a permission denied as soon as I move to the password line. What could I do? running it with root or setting tty=1 doesn't help. Thanks in advance.

**Comment by Evhorizon** [comment]
Update: I noticed that the pam file includes the login file that I don't have, I just have other and system-auth
