### ISSUE TITLE
[Documentation] How to update?

### ISSUE THREAD

**Issue by le-jun** [fairyglade/ly#551]
It's my first time using something from source, and everything [kinda works](#539) but I'm wondering, how should one update the whole thing once installed? Should I uninstall anything, just repeat the whole installation process, something else?

**Comment by AnErrupTion** [comment]
@le-jun To update, you can simply type `git pull` (if you cloned via Git, if not, redownload the latest source) and build & install the same way you did it the first time. I do think this should be mentionned in the README, however.
