### ISSUE TITLE
Error after login 

### ISSUE THREAD

**Issue by silviuXgaming** [fairyglade/ly#555]
yes, was works about 3 day and i have another glitch...on screen show like this ...
![SGCAM_0111012023_063946600](https://github.com/fairyglade/ly/assets/93388091/8b945658-7811-458b-81ad-d588ed6c3af1)

**Comment by LennyPhoenix** [comment]
Please try and provide more information so we can attempt to find a solution to your problem!

What kind of error is displayed? Are you able to copy it here, and if not is a screenshot or even a photo possible?

**Comment by silviuXgaming** [comment]
Now i uninstalled the "ly" . I was read better about compatibility of ly on arch + hyprland. tks for answer
![Uploading SGCAM_0411042023_102930795.jpg…]()

**Comment by LennyPhoenix** [comment]
hyprland is wayland, right? If so then Ly shouldn't be trying to run xorg, are you selecting the correct session?
