### ISSUE TITLE
Animation is displayed only after daemon restart

### ISSUE THREAD

**Issue by thirdpartyman** [fairyglade/ly#556]
Ly doesn't show animation on startup. 
To show animation I need to login and restart daemon via systemctl
`systemctl restart ly`
Then Ly will start with animation.

I use Arcolinux, Ly version 0.6.0
In /etc/ly/config.ini were changed only two lines:
```ini
animate = true
animation = 1
```

**Comment by umop3plsdn** [comment]
i'm having this exact issue as of late

**Comment by umop3plsdn** [comment]
NICE this fixed it! I appreciate your fix @SpaghettiBorgar
