### ISSUE TITLE
Characters and position are only correct after the first keypress

### ISSUE THREAD

**Issue by developer1105** [fairyglade/ly#561]
After the last update, Ly shows the login screen in the upper-right corner, and with weird characters in the box, instead of the correct ones. 

After pressing the first key (i.e. the first letter of the password), the poisiton is correct and the characters of the box are correct. 

What can this be?

**Comment by developer1105** [comment]
I think the problem has something to do with the transition from the default font/charset to the one specified by the user, via linux configurations. 

In a brief moment, everything is fine, soon after the boot, and then, when changing screen "resolution" (because somehow the user configured font is bigger), ly displays box's unexpected chars. 

Then, when a key is pressed, everything comes back to normal and the box is displayed with the expected characters.

**Comment by skyleo** [comment]
Running into the same issue on Arch with Ly version v0.6.0.r0.g1c2be47.

First key press does fix it as described.

**Comment by skyleo** [comment]
One thing I noticed is that either
- it doesn't happen at every boot
or
- it stops happening once the used username is saved in from a previous session.

**Comment by developer1105** [comment]
I have found a solution:
Remove sd-vconsole from the HOOKS (edit the file ```/etc/mkinitcpio.conf```)

So my hooks now look like this:
```HOOKS=(base udev modconf keyboard keymap block filesystems fsck)```

After editing mkinitcpio.conf, run this command to update the system:
```sudo mkinitcpio -P```
