### ISSUE TITLE
can't build files with make

### ISSUE THREAD

**Issue by gnmdrive** [fairyglade/ly#579]
hello, I can't build the project, this is the output of make:

```
make: uname: No such file or directory
building object obj/src/main.o
make: mkdir: No such file or directory
make: *** [makefile:51: obj/src/main.o] Error 127 
```

I don't understand why, can someone help me?

**Comment by anton-ptashnik** [comment]
build script cannot find Linux commands `uname` and `mkdir`, I suspect your PATH environment variable may be incomplete. Please open your terminal, cd into the repo dir and try:
```
cd /path/to/ly
PATH="/usr/bin:/bin:$PATH" # fix to locate missing commands
make
```
If it works then you need to make a permanent fix to restore your PATH

**Comment by AnErrupTion** [comment]
This issue doesn't look like an Ly issue. However, even if it was, the Zig rewrite uses the Zig build system which doesn't use those commands, so this issue should be fixed regardless.
