### ISSUE TITLE
How to complete remove (purge) on ubuntu ?

### ISSUE THREAD

**Issue by 3xploiton3** [fairyglade/ly#582]
OS: OS: Ubuntu 22.04.4 LTS x86_64

how to complete remove ly from my system?

similiar function like `sudo apt purge ly`

**Comment by AnErrupTion** [comment]
@3xploiton3 You should be able to remove `/usr/bin/ly` and the `/etc/ly` directory to remove all traces of Ly on your system. However, I do think an uninstall command should be available to ease that process up.

**Comment by AnErrupTion** [comment]
In the Zig rewrite, there's now an `uninstallall` command that can be called like so: `# zig build uninstallall`. The `build` might seem counter-intuitive, but this is required in order for Zig to execute the command we want.
