### ISSUE TITLE
Alpine i686: Ly fails

### ISSUE THREAD

**Issue by novaTopFlex** [fairyglade/ly#587]
I am currently attempting to build Ly on a QEMU virtual machine with the i686 32-bit version of x86 Alpine Linux and the latest 32-bit build of the distribution "distro" available. However, I am constantly failing to build Ly, and Alpine thinks that I am trying to utilize the "install" command on my system.

**Comment by AnErrupTion** [comment]
@novaTopFlex Could you check that this issue persists with master please?

**Comment by AnErrupTion** [comment]
Closing as stale + probably fixed as well.
