### ISSUE TITLE
Animations not loading on TTY (Arch, 6.8.2-arch2-1, Ly version v0.6.0.r0.g1c2be47)

### ISSUE THREAD

**Issue by amberjennings** [fairyglade/ly#592]
I'm able to get animations (PSX Doom fire, CMatrix) to display if I run `ly-dm` in a terminal in an active session, but those animations will not display on my TTY.

- WM (though doubtful of relevance) is sway 1.9
- Distribution and kernel version in the title
- Ly version in the title

This has been an issue since I started using ly (about a year ago). I'd really like to have these animations working.

**Comment by jahway603** [comment]
I'm experiencing the same issue on Artix with Sway 1.9 with version ly v0.6.0, released on Jun 15, 2023. I see this issue was closed, but **will a new release be happening soon to fix this "Animations not loading on TTY" issue?**

**Comment by amberjennings** [comment]
> I'm experiencing the same issue on Artix with Sway 1.9 with version ly v0.6.0, released on Jun 15, 2023. I see this issue was closed, but **will a new release be happening soon to fix this "Animations not loading on TTY" issue?**

I would recommend building from source (here) or installing the aur package `ly-git`

**Comment by AnErrupTion** [comment]
@jahway603 Yes, a new release is planned very soon!
