### ISSUE TITLE
Ly on external monitor?

### ISSUE THREAD

**Issue by kxmpxtxnt** [fairyglade/ly#595]
So im using Ly on my Laptop, is there a way to display the Login manager on one of my external monitors?

**Comment by AnErrupTion** [comment]
@kxmpxtxnt I think the default behavior of TTYs is to mirror themselves on every screen, and that should include Ly. Doesn't that happen already?

**Comment by AnErrupTion** [comment]
Does this only happen with Ly? Or maybe only with TTYs? In other words, can you use a GUI just fine? Because that may not be an issue with Ly directly.

**Comment by kxmpxtxnt** [comment]
So it works with some but with others it doesnt. But i fixed it, idk how. But its working now! Ty sir!
