### ISSUE TITLE
DESTDIR and NAME reintroduction

### ISSUE THREAD

**Issue by s7effeno** [fairyglade/ly#605]
Would it make sense for this project to bring back DESTDIR and NAME to build.zig from the old makefile? Take a look at [this](https://aur.archlinux.org/cgit/aur.git/commit/?h=ly-git&id=36441c49d7719f642e587e75403e20e809927f7c)

**Comment by AnErrupTion** [comment]
Ah yes, that's absolutely worth bringing back. I completely forgot this existed, to be honest 😅. I'll see what I can do probably next weekend.

Oh and by the way, the version for `ly-git` needs to be updated, since Ly is now tracking version 1.0.0 and not 0.6.0.

**Comment by s7effeno** [comment]
Thanks, would you consider tagging the point regarding the updated version?

**Comment by AnErrupTion** [comment]
What do you mean exactly by that? I plan on fixing a few more bugs at least before shipping 1.0.0.

**Comment by s7effeno** [comment]
The version will  automatically be updated after the new release then, you can see how `pkgver()` gets it. It's actually not recommended for me to manually edit for now.
