### ISSUE TITLE
Error in build.zig while trying to build from source

### ISSUE THREAD

**Issue by lukeflo** [fairyglade/ly#609]
I'm running Void Linux and want to install Ly as `systemd` free login manager for usage with `runit`.

Just cloned the repo and tried to build the binary, but get the following error after running `zig build`:

```
$ zig build
/home/<user>/Documents/packages/ly/build.zig:5:21: error: root struct of file 'std' has no member named 'Build'
pub fn build(b: *std.Build) void {
                 ~~~^~~~~~
referenced by:
    runBuild: /usr/lib/zig/build_runner.zig:231:45
    usage__anon_5110: /usr/lib/zig/build_runner.zig:242:13
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

Any idea what could cause this? I have absolutely no experience wit `zig`.

**Comment by AnErrupTion** [comment]
@lukeflo The version of Zig in the Void Linux repositories is way too old (0.10.1 vs 0.12.0), so you'll have to download Zig manually (https://ziglang.org/download, scroll down until you see 0.12.0) and compile Ly using that.

**Comment by lukeflo** [comment]
Oh, you're correct. Didn't see that Void only has 0.10. Will try it with the up to date Zig version today evening and report.

**Comment by lukeflo** [comment]
Ok, that did the trick. Unfortunately, `ly` is still not running. But thats another issue and I will try to solve it first myself...
