### ISSUE TITLE
FreeBSD 14.0 : unable to launch Sway

### ISSUE THREAD

**Issue by 2Belette** [fairyglade/ly#611]
I installed through `pkg install ly`, then I followed the pkg-message as follow : 

>     For install:
>         Add the following entry to /etc/gettytab:
> 
>         Ly:\
>         	:lo=/usr/local/bin/ly:\
>         	:al=root:
> 
>         Modify the command field of the ttyv1 terminal entry in /etc/ttys
> 
>         ttyv1   "/usr/libexec/getty Ly"         xterm   on secure
> 
>         Make sure that "tty" is set appropriately in the /usr/local/etc/ly/config.ini file if
>         you decide to configure a different TTY for Ly instead. 

I also did a `pkg install seatd` and added `seatd_enable="YES"` to `/etc/rc.conf` and added my user to video group.

I also added a export `XDG_RUNTIME_DIR=/var/run/user/`id -u`` to my `.zshrc`.

If I start sway from my terminal it is working all fine, but if I am trying from ly and selecting Sway it comes straight back with Logged Out.

I tried to add -d debug to seatd but not getting a lot here and don't know how to debug that.

I saw a couple of similar issues, but I can't find a working solution, if everyone has any idea ?

Many thanks

**Comment by AnErrupTion** [comment]
@2Belette Did you fix your issue in a specific way?
