### ISSUE TITLE
Zig Build - Hash Mismatch

### ISSUE THREAD

**Issue by dawosch** [fairyglade/ly#612]
When i try to build ly like on the readme explained, i get an error:
`Fetch Packages [2/2] zigini... /tmp/ly/build.zig.zon:11:21: error: hash mismatch: expected: 1220e7a99793a0430e0a7c0b938cb3c98321035bc297e21cd0e2413cf740b4923b9f, found: 12200dd136842068a2e82afb6ffd2821128140ca0b0fc59390a9bbe732d929eb75af
            .hash = "1220e7a99793a0430e0a7c0b938cb3c98321035bc297e21cd0e2413cf740b4923b9f",
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

Any ideas how to fix this?

**Comment by CaptainDolphy** [comment]
You appear to be using an outdated version of zig. As described in the Dependencies section of [readme.md](https://github.com/fairyglade/ly/blob/master/readme.md) the required version of zig is currently: `zig 0.12.0`

**Comment by AnErrupTion** [comment]
@dawosch As @CaptainDolphy said, you'll need Zig 0.12.0 to build Ly, as described in the README.
