### ISSUE TITLE
I can't Install Ly and the provided systemd service file 

### ISSUE THREAD

**Issue by CodeSwishKB** [fairyglade/ly#613]
I can't Install Ly and the provided systemd service file when running the "# zig build installsystemd". 

![image](https://github.com/fairyglade/ly/assets/101305133/c0f0e690-cd3c-48cd-b5c9-1cccca07c51b)

how can i fix this guys?

**Comment by AnErrupTion** [comment]
@CodeSwishKB The ``#`` means you need to run the command as root. You can do that using ``sudo``.
