### ISSUE TITLE
9wm not working

### ISSUE THREAD

**Issue by PINKeHamton** [fairyglade/ly#616]
9wm dose not show as a login in ly

**Comment by umop3plsdn** [comment]
you have to manually make a 9wm.desktop file in /usr/share/xsessions and /usr/share/wayland-sessions for wayland

**Comment by PINKeHamton** [comment]
9WM is a X11 Window Manager

**Comment by AnErrupTion** [comment]
@PINKeHamton You'll still need to add a `9wm.desktop` file in `/usr/share/xsessions` if you want Ly to recognize it. And, as @umop3plsdn has already suggested, you can just copy an existing desktop file and modify it accordingly (you'll probably just need to change the `Exec` and `Name` fields).
