### ISSUE TITLE
Zig 0.13.0+ build error

### ISSUE THREAD

**Issue by vexar-fantasy** [fairyglade/ly#618]
Hi, I just install Debian and I want to use Ly, I install necessary tools to install in Debian. I am using Zig version 0.14.0-dev. But when I run `zig build` and all other command have the same error like this: 

`/home/peter/ly/build.zig:32:33: error: no field named 'path' in union 'Build.LazyPath'
        .root_source_file = .{ .path = "src/main.zig" },`

`/home/peter/Downloads/zig-linux/lib/std/Build.zig:2185:22: note: union declared here
pub const LazyPath = union(enum) {`

`referenced by:
    runBuild__anon_8808: /home/peter/Downloads/zig-linux/lib/std/Build.zig:2130:27
    main: /home/peter/Downloads/zig-linux/lib/compiler/build_runner.zig:301:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces`
    
I have the same issue like the user Jabuxas in #614 
Hope this information will help to fix the issue!
Thanks a lot!

**Comment by mistermuki** [comment]
Try Zig 0.12.0

**Comment by AnErrupTion** [comment]
@vexar-fantasy This is most likely because Zig 0.13.0+ isn't supported by Ly yet. I do plan on adding support for it after #606 is merged.

**Comment by nmarks413** [comment]
@vexar-fantasy zig is an ever changing language and has not hit 1.0 yet. Breaking changes happen nearly constantly, so whenever you want to compile a zig project, make sure you use the recommended version (in this case 0.12.0)

**Comment by vexar-fantasy** [comment]
yep, thanks a lot, and sorry for reply late;-;
