### ISSUE TITLE
Ability to customize the UI.

### ISSUE THREAD

**Issue by RobertZenz** [fairyglade/ly#62]
Do you think it would be possible to add the ability to customize the UI from the configuration somehow? And would you be interested in such a feature?

Why I'm asking is that I'm really interested in using ly but I'd like it to have a more simple look. To be exact, I always liked how the TTY logins looked, it always felt kinda soothing to me (before being dumped into the compared noisy DEs). I could of course change the code to recreate such a look and feel, but it might be more worthwhile to add such a capability to ly in general. Though, I'm not sure whether you'd like such a feature or if it would be worth the effort.

**Comment by cylgom** [comment]
Hi, I think it depends how much customization you want: if it's something like removing the borders or positioning the window it's probably very easy to add. But honestly I don't understand what you mean by "tty login look", you could just login with the regular "login" from linux-util and run startx, could you explain in details what you have in mind? If you just want the regular "login" with an additional input for the DE there are already tools written in bash or python doing this (I don't remember their names, but I tested some before deciding to write Ly).

**Comment by RobertZenz** [comment]
Unfortunately the "bare" TTY login have a few drawbacks (two-step process, PAM not being initialized, no easy way to shutdown the system from the login screen, ...) so I'd rather have a display manager for that.

I was thinking about something like this, actually:

    +--------------------------------------------------------------------------+
    |username:                                                                 |
    |password:                                                                 |
    |session:     i3                                                           |
    |                                                                          |
    |                                                                          |
    |                                                                          |
    |                                                                          |
    |                                                                          |
    |                                                                          |
    |                                                                          |
    | hostname                                         F1 Shutdown   F2 Reboot |
    +--------------------------------------------------------------------------+

 > If you just want the regular "login" with an additional input for the DE there are already tools written in bash or python doing this (I don't remember their names, but I tested some before deciding to write Ly).

Are you talking about login managers like [CDM](https://github.com/evertiro/cdm) and [Console TDM](http://dopsi.github.io/console-tdm/)?

**Comment by cylgom** [comment]
Yes those are the ones I was thinking about. As for the customization what you are describing is exactly what could be easily added. I'll take a look when I have the time

**Comment by nullgemm** [comment]
Ok, this is not the focus right now, maybe one day, who knows...
