### ISSUE TITLE
"error: no field named 'path' in union 'Build.LazyPath'" on compilation attempt

### ISSUE THREAD

**Issue by mghalix** [fairyglade/ly#622]
## Steps to reproduce
- `git clone https://github.com/fairyglade/ly`
- `cd ly`
- `zig build`
- --

I am using **Zig version 0.13.0**
### trace
ly/build.zig:32:33: error: no field named 'path' in union 'Build.LazyPath'
        .root_source_file = .{ .path = "src/main.zig" },
                                ^~~~
/snap/zig/11625/lib/std/Build.zig:2171:22: note: union declared here
pub const LazyPath = union(enum) {
                     ^~~~~
referenced by:
    runBuild__anon_8826: /snap/zig/11625/lib/std/Build.zig:2116:27
    main: /snap/zig/11625/lib/compiler/build_runner.zig:301:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

**Comment by AnErrupTion** [comment]
@mghalix You need to use Zig 0.12.0, as specified in the README.
