### ISSUE TITLE
About adaptation 0.13

### ISSUE THREAD

**Issue by jinzhongjia** [fairyglade/ly#631]
Do you think it is necessary to adapt to 0.13 now?

The current situation is that some distributions use 0.12.1 and some distributions use 0.13.0

If adaptation is needed, I can be responsible for this part of the work. I checked a little the code that need to be changed, mainly the `zigini` package needs to be adjusted.

By the way, the current source file path of build.zig is not standardized. From version 12 , it is recommended to use `b.path`

**Comment by AnErrupTion** [comment]
Hey there! I actually have done some work locally to update to Zig 0.13.0 (in fact, the `zigini` library has already been updated), I'm just trying to reproduce & report a peculiar bug that resulted in us having to ship a hack in the build process. Thanks for proposing, though!

> Do you think it is necessary to adapt to 0.13 now?

It's not strictly necessary, but `master` targets the latest code and thus rolling-release distributions, such as Arch Linux (and the AUR in Arch's case). So I think it's okay to move to 0.13.0 already 😄

**Comment by christian-heusel** [comment]
Since we now also have zig 0.13 in the arch repos having compat for it would be cool!

**Comment by jinzhongjia** [comment]
> Since we now also have zig 0.13 in the arch repos having compat for it would be cool!

however, current zig `0.13` in arch is still under testing,  mine was installed from aur...

**Comment by christian-heusel** [comment]
> however, current zig 0.13 in arch is still under testing, mine was installed from aur...

It is not in the main repo 😅 I think it had to be upgraded in order to support llvm18
