### ISSUE TITLE
Failed to initialize user

### ISSUE THREAD

**Issue by vincent-thomas** [fairyglade/ly#633]
I get a message saying failed to initialize user for some reason. Can't give logs or anything because i don't know where they are and it should work

**Comment by vincent-thomas** [comment]
UPDATE: It doesn't work in tty, BUT it does work with `sudo ly` in terminal

**Comment by AnErrupTion** [comment]
@vincent-thomas What is your distribution, and how did you install Ly?

**Comment by vincent-thomas** [comment]
> @vincent-thomas What is your distribution, and how did you install Ly?

UPDATE: It works in both tty and with Xorg only with "sudo ly".

I used fedora workstation 40 and cloned the repo and compiled with the right version of zig. I checked the binaries where installed on my system like xauth mcookie so i don't understand what made it not work.

**Comment by AnErrupTion** [comment]
@vincent-thomas Then you'll need to either authorize Ly in SELinux or disable it altogether (although I do not recommend that last one). You could try and use the SELinux permission files from #310, though they may not work (anymore).

**Comment by AnErrupTion** [comment]
Closing this as a duplicate of #494.
