### ISSUE TITLE
Hide password prompt

### ISSUE THREAD

**Issue by KaiJan57** [fairyglade/ly#637]
In previous versions of ly, one could set asterik= (space) to make it harder to see the password length. This does not work anymore; I think ly could be improved by adding some password prompt display modes, like xsecurelock does, for example show the current time in hex on each keypress. This gives feedback on whether the key was recognized, but does not give away the password's length.

**Comment by AnErrupTion** [comment]
You can now set `asterisk = null` to not show the password at all.
