### ISSUE TITLE
(Gentoo) Ly autologs me out when I log in.

### ISSUE THREAD

**Issue by RIOT-DOT-OLD** [fairyglade/ly#641]
Using x11 w/ DWM. When I log in with username and password and try to login with both xinitrc and Xsession i get logged out immediately and I'm back to the Ly login screen.

**Comment by RIOT-DOT-OLD** [comment]
Having everything configured in my home folders .xinitrc file shouldn't be a problem right?

**Comment by RIOT-DOT-OLD** [comment]
Fixed it by rebooting after adding shebang to .xinitrc, didnt work automatically for some reason.

**Comment by AnErrupTion** [comment]
> Fixed it by rebooting after adding shebang to .xinitrc, didnt work automatically for some reason.

@RIOT-DOT-OLD The `.xinitrc` file is a script after all, so it needs to have a shebang.
