### ISSUE TITLE
error: root struct of file 'std' has no member named 'Build'

### ISSUE THREAD

**Issue by NETLIFYHOSTINGAHMD** [fairyglade/ly#645]
After git cloning the repo and running `zig build`, it does not compile.

https://0x0.st/XMQ7.png

I am running Void Linux with Runit on DWM.

Zig version is 0.10.1

**Comment by Scary-Guy** [comment]
"Zig version is 0.10.1"

Well there you go.  The requirements say you need Zig version 0.12.0

Also don't use version 0.13.0 either.  It does not work yet.  I tried.

**Comment by NETLIFYHOSTINGAHMD** [comment]
@Scary-Guy Oh! Thanks bro. I didn't read that, my bad.

**Comment by NETLIFYHOSTINGAHMD** [comment]
@Scary-Guy I did all the steps but when I rebooted it just puts me in the tty as per usual. 

ly shows up in /var/service
This is what `zig build run` looks like:
https://0x0.st/XMO7.png

**Comment by Scary-Guy** [comment]
> @Scary-Guy I did all the steps but when I rebooted it just puts me in the tty as per usual.
> 
> ly shows up in /var/service This is what `zig build run` looks like: https://0x0.st/XMO7.png

Unfortunately I'm not that far myself.  I have a post right below yours right now (issue #644) that I'm trying to figure out.

Also, as this is a new issue you should make a new thread for it (after searching all the current open threads for any similar issues so as not to make a duplicate.)

**Comment by AnErrupTion** [comment]
@NETLIFYHOSTINGAHMD Please open a new issue for this if it persists. Thanks!
