### ISSUE TITLE
Ly doesn't show up on boot after following all steps

### ISSUE THREAD

**Issue by NETLIFYHOSTINGAHMD** [fairyglade/ly#649]
Distro: Void
Init: Runit
Zig ver: 0.12.0

I did all the steps but when I rebooted it just puts me in the tty as per usual.

ly shows up in /var/service
This is what zig build run looks like:
https://0x0.st/XMO7.png

**Comment by nullptroma** [comment]
same is here

**Comment by NETLIFYHOSTINGAHMD** [comment]
> Try `chmod +x /var/service/ly/run`

Works. Thanks.

**Comment by NETLIFYHOSTINGAHMD** [comment]
> Try `chmod +x /var/service/ly/run`

Works. Thanks.

**Comment by AnErrupTion** [comment]
I think that's because the file permissions aren't properly set with the Zig code, and I'm still not sure why.
