### ISSUE TITLE
Configurable default `vi_mode`

### ISSUE THREAD

**Issue by v4run** [fairyglade/ly#657]
Hey, 

I have been trying out `ly` for the past few days. It's a cool project. One thing that I thought would be better to have is a way to configure the default vi mode when `vi_mode` is enabled. AFAIU, when `vi_mode` is enabled, it defaults to normal mode. So, I will have to switch to insert mode to enter the password 😅.  Is there a way to configure this already, that I missed? Thank you.

_I have a [fork](https://github.com/v4run/ly) with the said [change](https://github.com/v4run/ly/commit/68ff06ac9123b6ad6670e40d0a6119cc36240091). If this is something that makes sense to be part of `ly`, I would love to raise a PR_

**Comment by AnErrupTion** [comment]
@v4run So, if I understand, your change is to simply start Ly in insert mode when Vi mode is enabled, as opposed to starting in normal mode, correct?

**Comment by v4run** [comment]
Hmm, not exactly. Though, that is what I personally prefer. What I did was add another configuration parameter to choose the Vi mode to start with.

**Comment by AnErrupTion** [comment]
@v4run Right. In this case, go ahead and make a PR!
