### ISSUE TITLE
Version >= 0.6.0 including v1.0.1 just crashes! How to debug, see logs?

### ISSUE THREAD

**Issue by NuLL3rr0r** [fairyglade/ly#662]
### Pre-requisites

- [X] I have looked for any other duplicate issues

### Ly version

0.6.0 to 1.0.1

### Observed behavior

While v0.5.3 has been working fine for me for the past few years, any version newer than that just crashes at the start after a few seconds, even with the default configuration. I'm on Gentoo Linux.

### Expected behavior

It should not crash.

### Steps to reproduce

1. Just install/upgrade
2. Reboot
3. Wait 2/3 seconds and it crashes.

https://github.com/user-attachments/assets/81a554f3-b1e2-40b6-945b-19638f6c4aa6

### Relevant logs

```shell
I'm not sure where can I find these logs and where ly logs to.
```

**Comment by AnErrupTion** [comment]
@NuLL3rr0r Make sure the TTY where Ly spawns on is disabled. By default it's TTY 2, and it can be disabled using this command:

```
# rc-update del agetty.tty2
```

Of course, make sure to replace `tty2` with the one you're using (if you changed it).

**Comment by NuLL3rr0r** [comment]
Thank you @AnErrupTion ! I don't have any agetty.tty2 service running at boot:

```sh
$ rc-update del agetty.tty2

 * rc-update: service `agetty.tty2' is not in the runlevel `default'
```

But, the suggestion from [this commit](https://github.com/fairyglade/ly/pull/591/commits/7ff00c34c26a957612b7682fcd42c1ecaf42ef92) to remove the relevant line from `/etc/inittab` worked for me:

```
# Avoid resapwning a console on top of Ly
#c2:2345:respawn:/sbin/agetty 38400 tty2 linux
``` 

Though still wondering how v0.5.3 manages to not get affected by this.

**Comment by AnErrupTion** [comment]
> Though still wondering how v0.5.3 manages to not get affected by this.

I honestly have no idea, and searching through the commit logs & the old codebase to understand why this happens feels like a waste of time to me, especially when this isn't an Ly issue directly.

With that said, perhaps it'd be wise to add a post-install message in emerge (if those even exist) to inform the user about this? Also, since the information you were able to find is at the very end of the README, I'll be moving it to the OpenRC section which makes more sense.

**Comment by NuLL3rr0r** [comment]
That's a good enough idea for me. I will add your suggestion to my own ebuilds. Thank you! Will close the issue.
