### ISSUE TITLE
Xorg server messages on quitting WM

### ISSUE THREAD

**Issue by aerofractal** [fairyglade/ly#678]
Don't mean to dredge up old threads but I'm wondering if anyone has a solution to fix the shutdown messages on exiting your window manager when using the .desktop session file instead of ~/.xinitrc? 
Like in the OP, I have

`x_cmd = /usr/bin/X > /dev/null 2>&1` 

in my `config.ini` which takes care of the start messages, but I still get the X server messages on quitting before `ly` takes the TTY back over

_Originally posted by @aerofractal in https://github.com/fairyglade/ly/issues/338#issuecomment-2267880942_

**Comment by AnErrupTion** [comment]
@aerofractal Perhaps you can redirect the output directly inside `/etc/ly/xsetup.h` (or, if you're using `master`, `/etc/ly/setup.h`)?

**Comment by aerofractal** [comment]
Thanks for the reply, I should have clarified I am using the Arch package, I can pull and try to make the change and build from source, will let you know if the above suggestion works. Thanks!

**Comment by AnErrupTion** [comment]
@aerofractal My bad, I wrote `.h` instead of `.sh` :|
Since you're using the Arch package, you can simply modify `/etc/ly/xsetup.sh`.

**Comment by aerofractal** [comment]
So! Actually, applying the exact same routing as I am to `x_cmd` to `x_cmd_setup` works to silence the quit messages! My `x_cmd_setup` in `config.ini` now looks like:

`x_cmd_setup = /etc/ly/xsetup.sh > /dev/null 2>&1`

And I didn't have to actually edit `xsetup.sh` to make it work. Sorry, realize this probably isn't an Ly issue specifically, but that original thread was the only thing I was able to find related to the issue so far haha. Thanks for your help!
