### ISSUE TITLE
[Bug] 1.0.2 session immediatly logs out

### ISSUE THREAD

**Issue by JAicewizard** [fairyglade/ly#687]
### Pre-requisites

- [X] I have looked for any other duplicate issues

### Ly version

1.0.2 (arch)

### Observed behavior

When logging in with 1.0.2, the WM starts (i3, sway, gnome, etc) but then immediately exits again.

### Expected behavior

the WM should start

### Steps to reproduce

1. login

### Relevant logs

I looked at the journalCTL logs but could not find anything interesting, just confirming that the session immediately logged out.

This only happens on 1.0.2, 1.0.1 succesfully logs in without immediately logging off again, indicating a ly issue

**Comment by neodreen** [comment]
Same issue here with bspwm starting from .xinitrc

**Comment by JAicewizard** [comment]
For me the issue was a completely broken .profile, so I am going to close this as 100% my fault
