### ISSUE TITLE
[Bug] Error message of brightness commands displaying at current cursor position

### ISSUE THREAD

**Issue by moritz-reinel** [fairyglade/ly#695]
### Pre-requisites

- [X] I have looked for any other duplicate issues

### Ly version

1.1.0-dev.98+022d146

### Observed behavior

When executable for the `brightness_down_cmd` or `brightness_up_cmd` doesn't exist, the stderr output of the subprocess is displayed at the current cursor position

### Expected behavior

Either fail "silently" or add the error to the status bar.

I already noticed the (currently unused) lang item `err_brightness_change` which could be used in the status bar for implementation.

### Steps to reproduce

Set the config option `brightness_down_cmd` to any non-existent executable

### Relevant logs

```shell
                   ┌───────────────────────────────────────────────┐
                   │                                               │
                   │  <        failed to access console         >  │
                   │                                               │
                   │  x11      < Plasma (X11)                   >  │
                   │                                               │
                   │  login    /bin/sh: 1: /usr/bin/brightnessctl: not found
                   │                                               │
                   │  password                                     │
                   │                                               │
                   └───────────────────────────────────────────────┘
```

**Comment by moritz-reinel** [comment]
I have already looked into solving the problem and could open a PR, if appreciated :)

**Comment by AnErrupTion** [comment]
> I have already looked into solving the problem and could open a PR, if appreciated :)

That'd be greatly appreciated!

**Comment by AnErrupTion** [comment]
> I have a similar issue. In my case its an error message about a bluetooth device

That's a different issue. That's due to the TTY logs flowing into Ly's input fields.
