### ISSUE TITLE
zig build installsystemd has an error

### ISSUE THREAD

**Issue by vexar-fantasy** [fairyglade/ly#700]
Hi!, just switch back to Debian after a long time, I just tried to install Ly, it normal when I use `zig build installsystemd` it gave me error:

`warn: /etc/ly already exists as a directory.
warn: /etc already exists as a directory.
installsystemd
└─ installexe failure
error: AccessDenied
Build Summary: 5/7 steps succeeded; 1 failed (disable with --summary none)
installsystemd transitive failure
└─ installexe failure
error: the following build command failed with exit code 1:
/home/vexar/ly/zig-cache/o/29541fb3ea75ac28d067b34858fbc88c/build /home/vexar/zig-linux-x86_64-0.12.0/zig /home/vexar/ly /home/vexar/ly/zig-cache /home/vexar/.cache/zig --seed 0xa3b82683 -Zd538b8b0a307f1c8 installsystemd
vexar@v-laptop:~/ly$ zig build installsystemd --summary
expected [all|new|failures|none] after '--summary'

i've tried to use Zig 0.13, 0.14 and 0.12, but 3 of them have the same issue.

Hope to hear soon

**Comment by AnErrupTion** [comment]
@vexar-fantasy You need to run the command as root for it to succeed.

**Comment by vexar-fantasy** [comment]
I've tried `sudo` but it said 
`[sudo] password for vexar:`
 `sudo: zig: command not found`

Also, I've already added Zig to .bashrc

**Comment by AnErrupTion** [comment]
> I've tried `sudo` but it said `[sudo] password for vexar:` `sudo: zig: command not found`
> 
> Also, I've already added Zig to .bashrc

Ah yes, because the root user doesn't know about your Zig executable. You can try using the full path to Zig's executable if you so wish to.

**Comment by vexar-fantasy** [comment]
thanks, I'll try

**Comment by vexar-fantasy** [comment]
thanks @AnErrupTion for your support
